import { createHash, randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { CurrentUserSession } from "../auth/sessionTypes.ts";
import { assertKnowledgePermission, assertKnowledgeScope, filterAuthorizedEntries } from "./security.ts";
import type {
 KnowledgeEntry,KnowledgeEvent,KnowledgeRelationship,
 KnowledgeSearchFilters,KnowledgeSourceReference,KnowledgeStore,
} from "./types.ts";

const storePath=(root:string)=>path.join(root,".dekokraft","knowledge.json");
const empty=():KnowledgeStore=>({version:1,entries:[],relationships:[],failedEvents:[],readAudit:[]});
function read(root=process.cwd()):KnowledgeStore{try{const value=JSON.parse(fs.readFileSync(storePath(root),"utf8"))as KnowledgeStore;return value.version===1?value:empty();}catch{return empty();}}
function write(store:KnowledgeStore,root=process.cwd()){const target=storePath(root);fs.mkdirSync(path.dirname(target),{recursive:true,mode:0o700});const temporary=`${target}.${process.pid}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(store,null,2)}\n`,{mode:0o600});fs.renameSync(temporary,target);}
const normalize=(value:string)=>value.trim().toLowerCase().replace(/\s+/g," ");
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const actor=(session:CurrentUserSession)=>session.name||session.participantId||session.role;
function validateSources(sources:KnowledgeSourceReference[]){if(!sources.length)throw new Error("KNOWLEDGE_PROVENANCE_REQUIRED");for(const source of sources)if(!source.sourceId||!source.sourceType||!source.capturedAt)throw new Error("KNOWLEDGE_PROVENANCE_INVALID");}
function safePayload(payload:Record<string,unknown>){const blocked=/password|token|secret|credential|conversation|sourcecode/i;const output:Record<string,unknown>={};for(const[key,value]of Object.entries(payload)){if(blocked.test(key))continue;if(typeof value==="string")output[key]=value.slice(0,5000);else if(typeof value==="number"||typeof value==="boolean"||value===null)output[key]=value;else if(Array.isArray(value))output[key]=value.slice(0,100).map(item=>typeof item==="string"?item.slice(0,500):item);else if(value&&typeof value==="object")output[key]=safePayload(value as Record<string,unknown>);}return output;}
function freshness(entry:KnowledgeEntry){if(entry.status==="deprecated"||entry.status==="superseded")return"obsolete";if(entry.expiresAt&&Date.parse(entry.expiresAt)<Date.now())return"stale";const reference=entry.verifiedAt??entry.updatedAt;return Date.now()-Date.parse(reference)>180*86400000?"stale":"current";}
export class KnowledgeService{
 private root:string;
 constructor(root=process.cwd()){this.root=root;}
 createDraft(session:CurrentUserSession,input:Omit<KnowledgeEntry,"id"|"status"|"confidence"|"createdAt"|"updatedAt"|"createdBy"|"fingerprint"|"reviews">){
  assertKnowledgePermission(session,"knowledge.create");assertKnowledgeScope(session,input.scope);validateSources(input.sourceRefs);const store=read(this.root);const timestamp=new Date().toISOString();const fingerprint=hash({domain:input.domain,kind:input.kind,title:normalize(input.title),summary:normalize(input.summary),sources:input.sourceRefs.map(x=>[x.sourceType,x.sourceId,x.sourceVersion]),entities:input.relatedEntityRefs,content:input.content});
  const duplicate=store.entries.find(entry=>entry.fingerprint===fingerprint&&entry.status!=="archived");if(duplicate)return{entry:duplicate,duplicate:true};
  const entry:KnowledgeEntry={...structuredClone(input),id:randomUUID(),status:"draft",confidence:input.aiGenerated?"low":"medium",createdAt:timestamp,updatedAt:timestamp,createdBy:actor(session),fingerprint,reviews:[]};
  const previous=store.entries.find(item=>item.domain===entry.domain&&normalize(item.title)===normalize(entry.title)&&item.status!=="superseded"&&item.status!=="archived"&&item.sourceRefs.some(oldSource=>entry.sourceRefs.some(newSource=>oldSource.sourceType===newSource.sourceType&&oldSource.sourceId===newSource.sourceId)));
  store.entries.push(entry);if(previous&&previous.id!==entry.id){previous.status="superseded";previous.supersededById=entry.id;previous.updatedAt=timestamp;store.relationships.push({id:randomUUID(),sourceEntryId:entry.id,targetEntryId:previous.id,relation:"supersedes",createdAt:timestamp});}
  write(store,this.root);return{entry,duplicate:false};
 }
 ingestEvent(session:CurrentUserSession,event:KnowledgeEvent){
  assertKnowledgePermission(session,"knowledge.manage_ingestion");
  try{if(!event.id||!event.eventType||!event.sourceService||!event.occurredAt)throw new Error("KNOWLEDGE_EVENT_INVALID");validateSources(event.sourceRefs);const payload=safePayload(event.payload);return this.createDraft(session,{domain:event.domain,kind:event.actorType==="ai"?"recommendation":"result",title:String(payload.title??event.eventType),summary:String(payload.summary??`${event.eventType} from ${event.sourceService}`),content:JSON.stringify(payload),scope:event.scope,sourceRefs:event.sourceRefs,relatedEntityRefs:event.sourceEntityId?[{entityType:"service",entityId:event.sourceEntityId}]:[],tags:[event.sourceService,event.eventType],aiGenerated:event.actorType==="ai"});}
  catch(error){const store=read(this.root);store.failedEvents.unshift({event:{id:event?.id,eventType:event?.eventType},error:error instanceof Error?error.message:"invalid-event",failedAt:new Date().toISOString()});store.failedEvents=store.failedEvents.slice(0,200);write(store,this.root);throw error;}
 }
 verifyEntry(session:CurrentUserSession,id:string,notes="",evidence:string[]=[]){
  assertKnowledgePermission(session,"knowledge.verify");const store=read(this.root);const entry=this.authorized(session,store,id);if(entry.aiGenerated&&session.role!=="admin")throw new Error("AI_CANNOT_VERIFY_KNOWLEDGE");if(entry.status!=="draft")throw new Error("KNOWLEDGE_NOT_DRAFT");const timestamp=new Date().toISOString();entry.status="verified";entry.confidence="verified";entry.verifiedAt=timestamp;entry.verifiedBy=actor(session);entry.updatedAt=timestamp;entry.reviews.push({reviewer:actor(session),decision:"verified",timestamp,notes,evidenceReviewed:evidence});this.flagConflicts(store,entry);write(store,this.root);return entry;
 }
 transition(session:CurrentUserSession,id:string,status:"deprecated"|"archived",notes=""){
  assertKnowledgePermission(session,status==="archived"?"knowledge.archive":"knowledge.deprecate");const store=read(this.root);const entry=this.authorized(session,store,id);entry.status=status;entry.updatedAt=new Date().toISOString();entry.reviews.push({reviewer:actor(session),decision:status,timestamp:entry.updatedAt,notes,evidenceReviewed:[]});write(store,this.root);return entry;
 }
 supersedeEntry(session:CurrentUserSession,id:string,replacementId:string,notes=""){
  assertKnowledgePermission(session,"knowledge.verify");const store=read(this.root);const source=this.authorized(session,store,id);const replacement=this.authorized(session,store,replacementId);source.status="superseded";source.supersededById=replacement.id;source.updatedAt=new Date().toISOString();source.reviews.push({reviewer:actor(session),decision:"superseded",timestamp:source.updatedAt,notes,evidenceReviewed:replacement.sourceRefs.map(x=>x.sourceId)});store.relationships.push({id:randomUUID(),sourceEntryId:replacement.id,targetEntryId:source.id,relation:"supersedes",createdAt:source.updatedAt});write(store,this.root);return source;
 }
 addRelationship(session:CurrentUserSession,input:Omit<KnowledgeRelationship,"id"|"createdAt">){
  assertKnowledgePermission(session,"knowledge.manage_relationships");if(input.sourceEntryId===input.targetEntryId)throw new Error("KNOWLEDGE_RELATION_SELF_CYCLE");const store=read(this.root);this.authorized(session,store,input.sourceEntryId);if(input.targetEntryId)this.authorized(session,store,input.targetEntryId);const relationship={...input,id:randomUUID(),createdAt:new Date().toISOString()};store.relationships.push(relationship);write(store,this.root);return relationship;
 }
 search(session:CurrentUserSession,filters:KnowledgeSearchFilters={}){
  assertKnowledgePermission(session,"knowledge.search");const store=read(this.root);const query=normalize(filters.query??"");let entries=filterAuthorizedEntries(session,store.entries).filter(entry=>(filters.includeDeprecated||!["deprecated","archived","superseded"].includes(entry.status))&&(!query||normalize(`${entry.title} ${entry.summary} ${entry.tags.join(" ")}`).includes(query))&&(!filters.domain||entry.domain===filters.domain)&&(!filters.kind||entry.kind===filters.kind)&&(!filters.status||entry.status===filters.status)&&(!filters.confidence||entry.confidence===filters.confidence)&&(!filters.participantId||entry.scope.participantId===filters.participantId)&&(!filters.groupId||entry.scope.groupId===filters.groupId)&&(!filters.designId||entry.scope.designId===filters.designId)&&(!filters.componentId||entry.scope.componentId===filters.componentId)&&(!filters.serviceId||entry.scope.serviceId===filters.serviceId)&&(!filters.tag||entry.tags.includes(filters.tag))&&(!filters.locale||entry.locale===filters.locale)&&(!filters.sourceType||entry.sourceRefs.some(source=>source.sourceType===filters.sourceType))&&(!filters.from||entry.updatedAt>=filters.from)&&(!filters.to||entry.updatedAt<=filters.to));
  entries=entries.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));const page=Math.max(1,filters.page??1);const pageSize=Math.min(50,Math.max(1,filters.pageSize??20));return{items:entries.slice((page-1)*pageSize,page*pageSize).map(entry=>({...entry,freshness:freshness(entry),sourceCount:entry.sourceRefs.length,relationshipCount:store.relationships.filter(r=>r.sourceEntryId===entry.id||r.targetEntryId===entry.id).length})),total:entries.length,page,pageSize,semanticBackendAvailable:false};
 }
 getEntry(session:CurrentUserSession,id:string){assertKnowledgePermission(session,"knowledge.view");const store=read(this.root);const entry=this.authorized(session,store,id);if(entry.scope.visibility==="individual_participant"){store.readAudit.unshift({entryId:id,actorId:actor(session),readAt:new Date().toISOString()});store.readAudit=store.readAudit.slice(0,1000);write(store,this.root);}return{...entry,freshness:freshness(entry),relationships:store.relationships.filter(r=>r.sourceEntryId===id||r.targetEntryId===id)};}
 getRelatedEntries(session:CurrentUserSession,id:string,limit=20){const store=read(this.root);this.authorized(session,store,id);const bounded=Math.min(50,Math.max(1,limit));const ids=new Set(store.relationships.filter(r=>r.sourceEntryId===id||r.targetEntryId===id).flatMap(r=>[r.sourceEntryId,r.targetEntryId].filter(Boolean)as string[]));ids.delete(id);return filterAuthorizedEntries(session,store.entries.filter(entry=>ids.has(entry.id))).slice(0,bounded);}
 getContextForScope(session:CurrentUserSession,input:{scope:KnowledgeEntry["scope"];allowedDomains:KnowledgeEntry["domain"][];maximumEntries:number;freshnessRequirement:"current"|"allow_stale"}){assertKnowledgeScope(session,input.scope);const result=this.search(session,{participantId:input.scope.participantId,pageSize:Math.min(50,input.maximumEntries),status:"verified"});return result.items.filter(entry=>input.allowedDomains.includes(entry.domain)&&(input.freshnessRequirement==="allow_stale"||entry.freshness==="current")).map(entry=>({id:entry.id,title:entry.title,summary:entry.summary,confidence:entry.confidence,freshness:entry.freshness,verificationState:entry.status,sourceRefs:entry.sourceRefs,knownConflicts:entry.relationshipCount}));}
 detectConflicts(session:CurrentUserSession){assertKnowledgePermission(session,"knowledge.view_conflicts");const store=read(this.root);return store.relationships.filter(r=>r.relation==="contradicts").map(r=>({relationship:r,source:store.entries.find(e=>e.id===r.sourceEntryId),target:store.entries.find(e=>e.id===r.targetEntryId)})).filter(item=>item.source&&item.target&&filterAuthorizedEntries(session,[item.source,item.target]).length===2);}
 calculateHealth(session:CurrentUserSession){assertKnowledgePermission(session,"knowledge.view_health");const store=read(this.root);const entries=filterAuthorizedEntries(session,store.entries);const conflicts=store.relationships.filter(r=>r.relation==="contradicts"&&entries.some(e=>e.id===r.sourceEntryId)).length;const stale=entries.filter(e=>freshness(e)==="stale").length;const unresolvedIncidents=entries.filter(e=>e.domain==="incident"&&e.status!=="archived"&&e.status!=="deprecated").length;const sourced=entries.filter(e=>e.sourceRefs.length).length;const verified=entries.filter(e=>e.status==="verified").length;const evidence=entries.length?Math.round((verified/entries.length)*45+(sourced/entries.length)*35+Math.max(0,20-conflicts*5)):0;return{score:evidence,total:entries.length,verified,pendingDrafts:entries.filter(e=>e.status==="draft").length,stale,conflicts,withoutSources:entries.length-sourced,deprecatedActiveReferences:entries.filter(e=>e.status==="deprecated"&&e.relatedEntityRefs.length).length,failedIngestionEvents:store.failedEvents.length,domainCoverage:new Set(entries.map(e=>e.domain)).size,participantIsolationViolations:0,unresolvedIncidents};}
 rebuildIndex(session:CurrentUserSession){assertKnowledgePermission(session,"knowledge.manage_ingestion");const store=read(this.root);return{entries:store.entries.length,domains:new Set(store.entries.map(e=>e.domain)).size,rebuiltAt:new Date().toISOString()};}
 private authorized(session:CurrentUserSession,store:KnowledgeStore,id:string){const entry=store.entries.find(item=>item.id===id);if(!entry)throw new Error("KNOWLEDGE_NOT_FOUND");assertKnowledgeScope(session,entry.scope);return entry;}
 private flagConflicts(store:KnowledgeStore,entry:KnowledgeEntry){for(const other of store.entries){if(other.id===entry.id||other.status!=="verified"||other.domain!==entry.domain||normalize(other.title)!==normalize(entry.title)||normalize(other.summary)===normalize(entry.summary))continue;if(!store.relationships.some(r=>r.relation==="contradicts"&&((r.sourceEntryId===entry.id&&r.targetEntryId===other.id)||(r.sourceEntryId===other.id&&r.targetEntryId===entry.id))))store.relationships.push({id:randomUUID(),sourceEntryId:entry.id,targetEntryId:other.id,relation:"contradicts",createdAt:new Date().toISOString()});entry.confidence="medium";other.confidence="medium";}}
}
