import{participantAccessResponse,requireAuthenticatedUser}from"../../../lib/auth/participantAccess";import{conversationEngine}from"../../../lib/companion/conversationEngine";import type{ConversationPageContext,ReadablePageInput}from"../../../lib/companion/types";import type{ActionRequest}from"../../../lib/companion/actions/types";
function page(value:unknown):ConversationPageContext{const input=value&&typeof value==="object"?value as Record<string,unknown>:{};const pageType=input.pageType==="admin"||input.pageType==="participant"||input.pageType==="public"?input.pageType:"public";const locale=input.locale==="ar"||input.locale==="de"||input.locale==="fr"||input.locale==="en"?input.locale:"en";if(typeof input.pageId!=="string"||!input.pageId.trim())throw new Error("CONVERSATION_PAGE_REQUIRED");return{pageId:input.pageId.slice(0,300),pageType,locale,designId:typeof input.designId==="string"?input.designId:undefined,serviceId:typeof input.serviceId==="string"?input.serviceId:undefined,componentId:typeof input.componentId==="string"?input.componentId:undefined,participantId:typeof input.participantId==="string"?input.participantId:undefined,readableContent:input.readableContent as ReadablePageInput|undefined};}
export async function GET(request:Request){try{const actor=await requireAuthenticatedUser();const params=new URL(request.url).searchParams;const sessionId=params.get("sessionId");if(!sessionId)return Response.json({error:"sessionId-required"},{status:400});const context=params.get("context");if(context==="current")return Response.json({context:conversationEngine.readCurrentContext(actor,sessionId)});if(context==="previous")return Response.json({context:conversationEngine.readPreviousContext(actor,sessionId)});if(context==="history")return Response.json({contexts:conversationEngine.readContextHistory(actor,sessionId)});const memory=params.get("memory");if(memory==="current")return Response.json({memory:conversationEngine.readCurrentMemory(actor,sessionId)});if(memory==="recent")return Response.json({entries:conversationEngine.readRecentMemory(actor,sessionId,Number(params.get("limit")??10))});if(memory==="intent")return Response.json({intent:conversationEngine.readCurrentIntent(actor,sessionId)});if(memory==="topic")return Response.json({topic:conversationEngine.readCurrentTopic(actor,sessionId)});if(params.get("actions")==="history")return Response.json({history:conversationEngine.readActionHistory(actor,sessionId)});return Response.json({session:conversationEngine.snapshot(actor,sessionId)});}catch(error){return conversationError(error);}}
export async function POST(request:Request){try{const actor=await requireAuthenticatedUser();const body=await request.json()as Record<string,unknown>;
 if(body.action==="create_session")return Response.json({session:conversationEngine.createSession(actor,page(body.page))},{status:201});
 if(typeof body.sessionId!=="string")return Response.json({error:"sessionId-required"},{status:400});
 if(body.action==="message")return Response.json(await conversationEngine.process(actor,{sessionId:body.sessionId,text:typeof body.text==="string"?body.text:undefined,inputMode:body.inputMode==="voice"?"voice":"text",outputMode:"text",pageContext:body.pageContext&&typeof body.pageContext==="object"?body.pageContext as Partial<ConversationPageContext>:undefined}));
 if(body.action==="prepare_speech"){const speechDocument=body.sourceType==="page_reading"&&body.readableContent&&typeof body.readableContent==="object"?conversationEngine.preparePageSpeech(actor,{sessionId:body.sessionId,content:body.readableContent as ReadablePageInput}):conversationEngine.prepareSpeech(actor,{sessionId:body.sessionId,text:typeof body.text==="string"?body.text:undefined,source:{type:"conversation_reply",sourceId:body.sessionId}});return Response.json({speechDocument,providerConfigured:false});}
 if(body.action==="resolve_memory")return Response.json({references:conversationEngine.resolveMemoryReferences(actor,body.sessionId,typeof body.text==="string"?body.text:"")});
 if(body.action==="clear_memory")return Response.json({memory:conversationEngine.clearMemory(actor,body.sessionId)});
 if(body.action==="select_character")return Response.json({character:conversationEngine.selectCharacter(actor,body.sessionId,{characterId:typeof body.characterId==="string"?body.characterId:undefined,verbosity:body.verbosity==="minimal"||body.verbosity==="concise"||body.verbosity==="balanced"||body.verbosity==="detailed"?body.verbosity:undefined,disableConversationalLead:body.disableConversationalLead===true})});
 if(body.action==="execute_action"&&body.request&&typeof body.request==="object")return Response.json({result:await conversationEngine.executeAction(actor,body.sessionId,body.request as ActionRequest,body.confirmed===true)});
 if(body.action==="end_session"){conversationEngine.endSession(actor,body.sessionId);return Response.json({ended:true});}
 return Response.json({error:"invalid-conversation-action"},{status:400});
 }catch(error){return conversationError(error);}}
function conversationError(error:unknown){const message=error instanceof Error?error.message:"conversation-failed";if(message.startsWith("CONVERSATION_")||message.startsWith("VOICE_")||message.startsWith("READING_")||message.startsWith("SPEECH_")||message.startsWith("CHARACTER_"))return Response.json({error:message},{status:message.includes("ACCESS")||message.includes("SCOPE")?403:400});return participantAccessResponse(error);}
