export const defaultSellerId = "seller-001";

export const routes = {
  root: "/",
  welcome: "/welcome",
  home: "/home",
  market: "/market",
  login: "/login",
  register: "/register",
  studio: "/studio",
  smartEdit: ({ participantId, sellerId, productId }: { participantId?: string; sellerId?: string; productId?: string } = {}) => {
    const query = new URLSearchParams({ open: "smart-edit", workspace: "image" });
    if (participantId) query.set("participantId", participantId);
    if (sellerId) query.set("sellerId", sellerId);
    if (productId) query.set("productId", productId);
    return `/studio?${query.toString()}`;
  },
  studios: {
    laser: "/studio/laser",
    threeDForm: "/studio/3d-form",
    embroidery: "/studio/embroidery",
  },
  info: (section: string) => `/info/${section}`,
  category: (category: string) => `/${category}`,
  product: (category: string, product: string) => `/${category}/${product}`,
  store: (slug: string) => `/store/${slug}`,
  admin: {
    root: "/admin",
    pageDesigns: "/admin/page-designs",
    smartServices: "/admin/page-designs/smart-services",
    knowledge: "/admin/knowledge",
    missionControl: "/admin/mission-control",
    products: "/admin/products",
    orders: "/admin/orders",
    customers: "/admin/customers",
    analytics: "/admin/analytics",
    media: "/admin/media",
    earnings: "/admin/earnings",
    aiCost: "/admin/ai-cost",
    dekoClean: "/admin/dekoclean",
    inventory: "/admin/inventory",
    financial: "/admin/finance",
    financialLegacy: "/admin/financial",
    settings: "/admin/settings",
    studio: "/admin/studio",
    registrations: "/admin/registrations",
    participants: "/admin/sellers",
    participantDetail: (participantId: string) => `/admin/participants/${participantId}`,
    participantPreview: (participantId: string) => `/admin/participants/${participantId}/studio`,
    participantMaintenance: (participantId: string) => `/admin/participants/${participantId}/maintenance`,
    participantOwnershipDebug: "/admin/debug/participant-ownership",
    newSeller: "/admin/sellers/new",
    dekoBrain: (section: string) => `/admin/dekobrain/${section}`,
    studioTool: (tool: string) => `/admin/studio/${tool}`,
  },
  participant: {
    root: "/participant",
    brandStudio: "/participant/brand-studio",
    orders: "/participant/orders",
    customers: "/participant/customers",
    analytics: "/participant/analytics",
    media: "/participant/media",
    earnings: "/participant/earnings",
    settings: "/participant/settings",
    studio: "/participant/studio",
    studioTools: "/participant/studio/tools",
    aiCost: "/participant/ai-cost",
    invoices: "/participant/invoices",
    inventory: "/participant/inventory",
    maintenance: "/participant/maintenance",
    support: "/participant/support",
  },
  seller: {
    login: "/seller/login",
    dashboard: "/seller/dashboard",
    invite: "/seller/accept-invite",
    root: (sellerId = defaultSellerId) => `/seller/${sellerId}`,
    products: (sellerId = defaultSellerId) => `/seller/${sellerId}/products`,
    newProduct: (sellerId = defaultSellerId) => `/seller/${sellerId}/products/new`,
    product: (sellerId: string, productId: string) => `/seller/${sellerId}/products/${productId}`,
    orders: (sellerId = defaultSellerId) => `/seller/${sellerId}/orders`,
    customers: (sellerId = defaultSellerId) => `/seller/${sellerId}/customers`,
    analytics: (sellerId = defaultSellerId) => `/seller/${sellerId}/analytics`,
    media: (sellerId = defaultSellerId) => `/seller/${sellerId}/media`,
    earnings: (sellerId = defaultSellerId) => `/seller/${sellerId}/earnings`,
    profile: (sellerId = defaultSellerId) => `/seller/${sellerId}/profile`,
    settings: (sellerId = defaultSellerId) => `/seller/${sellerId}/settings/store`,
    studio: (sellerId = defaultSellerId) => `/seller/${sellerId}/studio`,
    aiCost: (sellerId = defaultSellerId) => `/seller/${sellerId}/ai-cost`,
    invoices: (sellerId = defaultSellerId) => `/seller/${sellerId}/invoices`,
    inventory: (sellerId = defaultSellerId) => `/seller/${sellerId}/inventory`,
    support: (sellerId = defaultSellerId) => `/seller/${sellerId}/support`,
  },
} as const;

export const requiredPublicRoutes = [
  routes.root,
  routes.welcome,
  routes.home,
  routes.market,
  routes.login,
  routes.register,
  routes.studio,
  routes.studios.laser,
  routes.studios.threeDForm,
  routes.studios.embroidery,
  routes.admin.root,
  routes.admin.pageDesigns,
  routes.admin.studio,
  routes.participant.root,
  routes.participant.studio,
  routes.seller.root(),
  routes.category("candles"),
  routes.category("gift"),
  routes.category("kids"),
  routes.category("services"),
  routes.product("candles", "candel-001"),
  routes.product("gift", "gift-001"),
  routes.product("kids", "rosememory-001"),
  routes.product("services", "service-01"),
] as const;

export const routeAuditPaths = [
  ...requiredPublicRoutes,
  routes.admin.products,
  routes.admin.pageDesigns,
  routes.admin.orders,
  routes.admin.customers,
  routes.admin.analytics,
  routes.admin.media,
  routes.admin.earnings,
  routes.admin.aiCost,
  routes.admin.dekoClean,
  routes.admin.inventory,
  routes.admin.financial,
  routes.admin.financialLegacy,
  routes.admin.settings,
  routes.admin.registrations,
  routes.admin.participants,
  routes.admin.newSeller,
  routes.participant.orders,
  routes.participant.customers,
  routes.participant.analytics,
  routes.participant.media,
  routes.participant.earnings,
  routes.participant.settings,
  routes.participant.studioTools,
  routes.participant.aiCost,
  routes.participant.invoices,
  routes.participant.inventory,
  routes.participant.maintenance,
  routes.participant.support,
  routes.seller.login,
  routes.seller.dashboard,
  routes.seller.invite,
  routes.seller.products(),
  routes.seller.newProduct(),
  routes.seller.orders(),
  routes.seller.customers(),
  routes.seller.analytics(),
  routes.seller.media(),
  routes.seller.earnings(),
  routes.seller.profile(),
  routes.seller.settings(),
  routes.seller.studio(),
  routes.seller.aiCost(),
  routes.seller.invoices(),
  routes.seller.inventory(),
  routes.seller.support(),
  routes.store("dekokraft-demo"),
  routes.store("wooden-boxes"),
  routes.store("light-workshop"),
  routes.info("about"),
  routes.info("legal"),
  routes.admin.dekoBrain("product-identity"),
  routes.admin.dekoBrain("echo-learning"),
  routes.admin.dekoBrain("knowledge-tree"),
  routes.admin.dekoBrain("living-identity"),
  routes.admin.studioTool("media"),
  routes.admin.studioTool("extract"),
  routes.admin.studioTool("backgrounds"),
  routes.admin.studioTool("product-preview"),
  routes.admin.studioTool("webp"),
  routes.admin.studioTool("canva"),
  routes.admin.studioTool("marketing-ai"),
] as const;
