import type { Lang, LocaleMessages } from "./types.ts";
import { welcomeTranslations } from "./welcome.ts";

type FoundationMessages = Pick<
  LocaleMessages,
  | "toolbar"
  | "homepage"
  | "categories"
  | "products"
  | "participant"
  | "seller"
  | "market"
  | "login"
  | "register"
  | "dashboard"
  | "dekoBrain"
  | "notifications"
  | "buttons"
  | "errors"
  | "footer"
  | "welcome"
>;

export const foundationMessages: Record<Lang, FoundationMessages> = {
  ar: {
    welcome: welcomeTranslations.ar,
    toolbar: { menu: "القائمة", settings: "الإعدادات", language: "اللغة", market: "السوق", login: "تسجيل الدخول", account: "الحساب", favorites: "المفضلة", cart: "سلة التسوق", search: "البحث", openMenu: "فتح القائمة", openSettings: "فتح الإعدادات", changeLanguage: "تغيير اللغة", openMarket: "فتح سوق DekoKraft", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", participantAnnouncements: "إعلان المشاركين", mainAnnouncement: "الإعلان الرئيسي" },
    homepage: { eyebrow: "DekoKraft", title: "DekoKraft", sectionsEyebrow: "أقسام المنصة", sectionsTitle: "أقسام DekoKraft", marketEyebrow: "السوق", marketTitle: "استكشف السوق", latestEyebrow: "أحدث المنتجات", latestTitle: "أحدث المنتجات" },
    categories: { notFound: "القسم غير موجود" }, products: { categoryLabel: "فئة المنتج" },
    participant: { title: "لوحة المشارك", studio: "استوديو المشارك" },
    seller: { dashboard: "لوحة البائع", login: "دخول البائع", logout: "تسجيل الخروج", stores: "متاجر البائعين", profile: "الملف الشخصي", accountMenu: "فتح قائمة الحساب", studioTitle: "استوديو المشارك", welcome: "مرحبًا {name}، تابع منتجاتك وطلباتك وأداء متجرك من مكان واحد.", addProduct: "إضافة منتج", openStudio: "فتح Studio", previewStore: "معاينة متجري", statsLabel: "إحصائيات المشارك", productCount: "عدد المنتجات", published: "المنشورة", drafts: "المسودات", underReview: "تحت المراجعة", lowStock: "منخفضة المخزون", averageEcho: "متوسط Echo Score", smartReview: "مراجعة ذكية", attentionTitle: "منتجات تحتاج إلى اهتمام", viewAllProducts: "عرض كل المنتجات", noAttention: "لا توجد منتجات تحتاج إلى اهتمام حاليًا.", products: "منتجاتي", orders: "طلباتي", customers: "عملائي", analytics: "الإحصائيات", media: "الصور والتعديل الذكي", earnings: "المبيعات والأرباح", settings: "إعدادات المتجر", studio: "الاستوديو", aiCost: "تكلفة الذكاء الاصطناعي", invoices: "الفواتير والتقارير", inventory: "المخزون والمواد", support: "الدعم", navigationLabel: "تنقل استوديو المشارك", preparing: "قيد التجهيز", storeSettings: "إعدادات المتجر", developmentSwitch: "تبديل حساب الاختبار", backToSite: "العودة إلى الموقع", status: { active: "نشط", invited: "بانتظار قبول الدعوة", paused: "متوقف مؤقتًا", suspended: "موقوف إداريًا" } },
    market: { title: "سوق DekoKraft", description: "اكتشف المنتجات والحرف والخدمات.", storeNotFound: "المتجر غير موجود", backHome: "العودة إلى DekoKraft", logoAlt: "شعار {name}", languages: "اللغات", storeCategories: "فئات المتجر", fromStore: "من المتجر", publishedProducts: "المنتجات المنشورة", noPublishedProducts: "لا توجد منتجات منشورة في هذا المتجر حاليًا." },
    login: { title: "دخول البائع", submit: "دخول إلى لوحة البائع", description: "ادخل إلى لوحة متجرك باستخدام حساب النسخة المحلية التجريبية.", email: "البريد الإلكتروني", password: "كلمة المرور التجريبية", passwordRequired: "أدخل كلمة المرور التجريبية.", failed: "تعذر تسجيل الدخول.", testAccountMissing: "تعذر العثور على حساب الاختبار.", quickFailed: "تعذر تسجيل الدخول السريع.", testAccounts: "حسابات الاختبار", testAccountsDescription: "اختر حسابًا لفتح لوحة البائع مباشرة.", quickLogin: "دخول سريع: {id}" }, register: { title: "إنشاء حساب", submit: "إنشاء الحساب", inviteLoading: "جارٍ تحميل الدعوة...", inviteNotFound: "الدعوة غير موجودة", inviteTitle: "قبول دعوة البائع", sellerName: "اسم البائع", storeName: "اسم المتجر", email: "البريد الإلكتروني", acceptInvite: "قبول الدعوة" },
    dashboard: { title: "لوحة التحكم" }, dekoBrain: { title: "DekoBrain", description: "ذكاء محلي لفهم هوية المنتج والتعلم من القرارات." },
    notifications: { success: "تمت العملية بنجاح.", error: "تعذر إكمال العملية." },
    buttons: { open: "فتح", close: "إغلاق", save: "حفظ", cancel: "إلغاء", back: "رجوع", next: "التالي" },
    errors: { generic: "حدث خطأ غير متوقع.", missingTranslation: "الترجمة غير متوفرة" },
    footer: { description: "مساحة للحرف والمنتجات والمجتمع.", sellerLogin: "دخول البائع", sellerDashboard: "لوحة البائع", admin: "الإدارة", navigationLabel: "روابط DekoKraft", rights: "جميع الحقوق محفوظة", legalLinks: "الروابط القانونية", top: "الأعلى ↑" },
  },
  en: {
    welcome: welcomeTranslations.en,
    toolbar: { menu: "Menu", settings: "Settings", language: "Language", market: "Market", login: "Log in", account: "Account", favorites: "Favorites", cart: "Cart", search: "Search", openMenu: "Open menu", openSettings: "Open settings", changeLanguage: "Change language", openMarket: "Open DekoKraft market", signIn: "Sign in", signOut: "Sign out", participantAnnouncements: "Participant Announcements", mainAnnouncement: "Main Announcement" },
    homepage: { eyebrow: "DekoKraft", title: "DekoKraft", sectionsEyebrow: "Platform sections", sectionsTitle: "DekoKraft sections", marketEyebrow: "Marketplace", marketTitle: "Explore the marketplace", latestEyebrow: "Latest products", latestTitle: "Latest products" },
    categories: { notFound: "Category not found" }, products: { categoryLabel: "Product category" },
    participant: { title: "Participant dashboard", studio: "Participant studio" },
    seller: { dashboard: "Seller dashboard", login: "Seller login", logout: "Log out", stores: "Seller stores", profile: "Profile", accountMenu: "Open account menu", studioTitle: "Participant studio", welcome: "Welcome {name}. Manage your products, orders, and store performance in one place.", addProduct: "Add product", openStudio: "Open Studio", previewStore: "Preview my store", statsLabel: "Participant statistics", productCount: "Products", published: "Published", drafts: "Drafts", underReview: "Under review", lowStock: "Low stock", averageEcho: "Average Echo Score", smartReview: "Smart review", attentionTitle: "Products needing attention", viewAllProducts: "View all products", noAttention: "No products need attention right now.", products: "My products", orders: "My orders", customers: "My customers", analytics: "Analytics", media: "Images & Smart Edit", earnings: "Sales & Earnings", settings: "Store settings", studio: "Studio", aiCost: "AI cost", invoices: "Invoices & Reports", inventory: "Inventory & Materials", support: "Support", navigationLabel: "Participant studio navigation", preparing: "Coming soon", storeSettings: "Store settings", developmentSwitch: "Switch test account", backToSite: "Back to site", status: { active: "Active", invited: "Invitation pending", paused: "Paused", suspended: "Suspended" } },
    market: { title: "DekoKraft marketplace", description: "Discover products, crafts, and services.", storeNotFound: "Store not found", backHome: "Back to DekoKraft", logoAlt: "{name} logo", languages: "Languages", storeCategories: "Store categories", fromStore: "From the store", publishedProducts: "Published products", noPublishedProducts: "This store has no published products yet." },
    login: { title: "Seller login", submit: "Open seller dashboard", description: "Access your store dashboard with a local demo account.", email: "Email address", password: "Demo password", passwordRequired: "Enter the demo password.", failed: "Unable to sign in.", testAccountMissing: "The test account could not be found.", quickFailed: "Quick login failed.", testAccounts: "Test accounts", testAccountsDescription: "Choose an account to open its seller dashboard directly.", quickLogin: "Quick login: {id}" }, register: { title: "Create account", submit: "Create account", inviteLoading: "Loading invitation...", inviteNotFound: "Invitation not found", inviteTitle: "Accept seller invitation", sellerName: "Seller name", storeName: "Store name", email: "Email address", acceptInvite: "Accept invitation" },
    dashboard: { title: "Dashboard" }, dekoBrain: { title: "DekoBrain", description: "Local intelligence for product identity and decision-based learning." },
    notifications: { success: "Completed successfully.", error: "The operation could not be completed." },
    buttons: { open: "Open", close: "Close", save: "Save", cancel: "Cancel", back: "Back", next: "Next" },
    errors: { generic: "An unexpected error occurred.", missingTranslation: "Translation unavailable" },
    footer: { description: "A space for crafts, products, and community.", sellerLogin: "Seller login", sellerDashboard: "Seller dashboard", admin: "Administration", navigationLabel: "DekoKraft links", rights: "All rights reserved", legalLinks: "Legal links", top: "Top ↑" },
  },
  de: {
    welcome: welcomeTranslations.de,
    toolbar: { menu: "Menü", settings: "Einstellungen", language: "Sprache", market: "Markt", login: "Einloggen", account: "Konto", favorites: "Favoriten", cart: "Warenkorb", search: "Suche", openMenu: "Menü öffnen", openSettings: "Einstellungen öffnen", changeLanguage: "Sprache ändern", openMarket: "DekoKraft-Markt öffnen", signIn: "Anmelden", signOut: "Abmelden", participantAnnouncements: "Teilnehmeranzeigen", mainAnnouncement: "Hauptankündigung" },
    homepage: { eyebrow: "DekoKraft", title: "DekoKraft", sectionsEyebrow: "Bereiche der Plattform", sectionsTitle: "DekoKraft Bereiche", marketEyebrow: "Marktplatz", marketTitle: "Marktplatz entdecken", latestEyebrow: "Neueste Produkte", latestTitle: "Neueste Produkte" },
    categories: { notFound: "Kategorie nicht gefunden" }, products: { categoryLabel: "Produktkategorie" },
    participant: { title: "Teilnehmer-Dashboard", studio: "Teilnehmer-Studio" },
    seller: { dashboard: "Verkäufer-Dashboard", login: "Verkäufer-Login", logout: "Ausloggen", stores: "Verkäufer-Shops", profile: "Profil", accountMenu: "Kontomenü öffnen", studioTitle: "Teilnehmer-Studio", welcome: "Willkommen {name}. Verwalten Sie Produkte, Bestellungen und Shop-Leistung an einem Ort.", addProduct: "Produkt hinzufügen", openStudio: "Studio öffnen", previewStore: "Meinen Shop ansehen", statsLabel: "Teilnehmer-Statistiken", productCount: "Produkte", published: "Veröffentlicht", drafts: "Entwürfe", underReview: "In Prüfung", lowStock: "Niedriger Bestand", averageEcho: "Durchschnittlicher Echo Score", smartReview: "Intelligente Prüfung", attentionTitle: "Produkte mit Handlungsbedarf", viewAllProducts: "Alle Produkte anzeigen", noAttention: "Derzeit benötigen keine Produkte Ihre Aufmerksamkeit.", products: "Meine Produkte", orders: "Meine Bestellungen", customers: "Meine Kunden", analytics: "Statistiken", media: "Bilder & Smart Edit", earnings: "Verkäufe & Einnahmen", settings: "Shop-Einstellungen", studio: "Studio", aiCost: "KI-Kosten", invoices: "Rechnungen & Berichte", inventory: "Bestand & Materialien", support: "Support", navigationLabel: "Navigation des Teilnehmer-Studios", preparing: "In Vorbereitung", storeSettings: "Shop-Einstellungen", developmentSwitch: "Testkonto wechseln", backToSite: "Zurück zur Website", status: { active: "Aktiv", invited: "Einladung ausstehend", paused: "Pausiert", suspended: "Gesperrt" } },
    market: { title: "DekoKraft Marktplatz", description: "Produkte, Handwerk und Dienstleistungen entdecken.", storeNotFound: "Shop nicht gefunden", backHome: "Zurück zu DekoKraft", logoAlt: "Logo von {name}", languages: "Sprachen", storeCategories: "Shop-Kategorien", fromStore: "Aus dem Shop", publishedProducts: "Veröffentlichte Produkte", noPublishedProducts: "Dieser Shop hat derzeit keine veröffentlichten Produkte." },
    login: { title: "Verkäufer-Login", submit: "Verkäufer-Dashboard öffnen", description: "Öffnen Sie Ihr Shop-Dashboard mit einem lokalen Demo-Konto.", email: "E-Mail-Adresse", password: "Demo-Passwort", passwordRequired: "Geben Sie das Demo-Passwort ein.", failed: "Anmeldung nicht möglich.", testAccountMissing: "Das Testkonto wurde nicht gefunden.", quickFailed: "Schnellanmeldung fehlgeschlagen.", testAccounts: "Testkonten", testAccountsDescription: "Wählen Sie ein Konto, um das Verkäufer-Dashboard direkt zu öffnen.", quickLogin: "Schnellzugang: {id}" }, register: { title: "Konto erstellen", submit: "Konto erstellen", inviteLoading: "Einladung wird geladen...", inviteNotFound: "Einladung nicht gefunden", inviteTitle: "Verkäufereinladung annehmen", sellerName: "Name des Verkäufers", storeName: "Shopname", email: "E-Mail-Adresse", acceptInvite: "Einladung annehmen" },
    dashboard: { title: "Dashboard" }, dekoBrain: { title: "DekoBrain", description: "Lokale Intelligenz für Produktidentität und Lernen aus Entscheidungen." },
    notifications: { success: "Erfolgreich abgeschlossen.", error: "Der Vorgang konnte nicht abgeschlossen werden." },
    buttons: { open: "Öffnen", close: "Schließen", save: "Speichern", cancel: "Abbrechen", back: "Zurück", next: "Weiter" },
    errors: { generic: "Ein unerwarteter Fehler ist aufgetreten.", missingTranslation: "Übersetzung nicht verfügbar" },
    footer: { description: "Ein Ort für Handwerk, Produkte und Gemeinschaft.", sellerLogin: "Verkäufer-Login", sellerDashboard: "Verkäufer-Dashboard", admin: "Verwaltung", navigationLabel: "DekoKraft Links", rights: "Alle Rechte vorbehalten", legalLinks: "Rechtliche Links", top: "Nach oben ↑" },
  },
  fr: {
    welcome: welcomeTranslations.fr,
    toolbar: { menu: "Menu", settings: "Paramètres", language: "Langue", market: "Marché", login: "Connexion", account: "Compte", favorites: "Favoris", cart: "Panier", search: "Recherche", openMenu: "Ouvrir le menu", openSettings: "Ouvrir les paramètres", changeLanguage: "Changer de langue", openMarket: "Ouvrir le marché DekoKraft", signIn: "Se connecter", signOut: "Se déconnecter", participantAnnouncements: "Annonces des participants", mainAnnouncement: "Annonce principale" },
    homepage: { eyebrow: "DekoKraft", title: "DekoKraft", sectionsEyebrow: "Sections de la plateforme", sectionsTitle: "Sections DekoKraft", marketEyebrow: "Marché", marketTitle: "Explorer le marché", latestEyebrow: "Derniers produits", latestTitle: "Derniers produits" },
    categories: { notFound: "Catégorie introuvable" }, products: { categoryLabel: "Catégorie du produit" },
    participant: { title: "Tableau du participant", studio: "Studio du participant" },
    seller: { dashboard: "Tableau du vendeur", login: "Connexion vendeur", logout: "Déconnexion", stores: "Boutiques vendeurs", profile: "Profil", accountMenu: "Ouvrir le menu du compte", studioTitle: "Studio participant", welcome: "Bienvenue {name}. Gérez vos produits, commandes et performances depuis un seul endroit.", addProduct: "Ajouter un produit", openStudio: "Ouvrir Studio", previewStore: "Voir ma boutique", statsLabel: "Statistiques du participant", productCount: "Produits", published: "Publiés", drafts: "Brouillons", underReview: "En révision", lowStock: "Stock faible", averageEcho: "Score Echo moyen", smartReview: "Révision intelligente", attentionTitle: "Produits nécessitant votre attention", viewAllProducts: "Voir tous les produits", noAttention: "Aucun produit ne nécessite votre attention actuellement.", products: "Mes produits", orders: "Mes commandes", customers: "Mes clients", analytics: "Statistiques", media: "Images et retouche intelligente", earnings: "Ventes et revenus", settings: "Paramètres de la boutique", studio: "Studio", aiCost: "Coûts IA", invoices: "Factures et rapports", inventory: "Stock et matériaux", support: "Assistance", navigationLabel: "Navigation du studio participant", preparing: "En préparation", storeSettings: "Paramètres de la boutique", developmentSwitch: "Changer de compte test", backToSite: "Retour au site", status: { active: "Actif", invited: "Invitation en attente", paused: "En pause", suspended: "Suspendu" } },
    market: { title: "Marché DekoKraft", description: "Découvrez les produits, l’artisanat et les services.", storeNotFound: "Boutique introuvable", backHome: "Retour à DekoKraft", logoAlt: "Logo de {name}", languages: "Langues", storeCategories: "Catégories de la boutique", fromStore: "Dans la boutique", publishedProducts: "Produits publiés", noPublishedProducts: "Cette boutique n’a actuellement aucun produit publié." },
    login: { title: "Connexion vendeur", submit: "Ouvrir le tableau vendeur", description: "Accédez au tableau de votre boutique avec un compte de démonstration local.", email: "Adresse e-mail", password: "Mot de passe de démonstration", passwordRequired: "Saisissez le mot de passe de démonstration.", failed: "Connexion impossible.", testAccountMissing: "Le compte de test est introuvable.", quickFailed: "La connexion rapide a échoué.", testAccounts: "Comptes de test", testAccountsDescription: "Choisissez un compte pour ouvrir directement son tableau vendeur.", quickLogin: "Connexion rapide : {id}" }, register: { title: "Créer un compte", submit: "Créer le compte", inviteLoading: "Chargement de l’invitation...", inviteNotFound: "Invitation introuvable", inviteTitle: "Accepter l’invitation vendeur", sellerName: "Nom du vendeur", storeName: "Nom de la boutique", email: "Adresse e-mail", acceptInvite: "Accepter l’invitation" },
    dashboard: { title: "Tableau de bord" }, dekoBrain: { title: "DekoBrain", description: "Intelligence locale pour l’identité produit et l’apprentissage par décisions." },
    notifications: { success: "Opération réussie.", error: "L’opération n’a pas pu être terminée." },
    buttons: { open: "Ouvrir", close: "Fermer", save: "Enregistrer", cancel: "Annuler", back: "Retour", next: "Suivant" },
    errors: { generic: "Une erreur inattendue est survenue.", missingTranslation: "Traduction indisponible" },
    footer: { description: "Un espace pour l’artisanat, les produits et la communauté.", sellerLogin: "Connexion vendeur", sellerDashboard: "Tableau vendeur", admin: "Administration", navigationLabel: "Liens DekoKraft", rights: "Tous droits réservés", legalLinks: "Liens juridiques", top: "Haut ↑" },
  },
};
