"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useLanguage } from "../../../components/LanguageProvider";
import type { KnowledgeEntry, KnowledgeRelationship } from "../../../../lib/knowledge/types";
type Entry=KnowledgeEntry&{freshness:string;relationships:KnowledgeRelationship[]};
type Data={entry?:Entry;related?:KnowledgeEntry[];error?:string};
export default function KnowledgeEntryView({entryId}:{entryId:string}){
 const{lang}=useLanguage();const[data,setData]=useState<Data>({});const[expanded,setExpanded]=useState(false);const[message,setMessage]=useState("");const load=useCallback(async()=>{const r=await fetch(`/api/knowledge?mode=entry&id=${encodeURIComponent(entryId)}&limit=20`,{cache:"no-store"});const x=await r.json()as Data;if(!r.ok)throw new Error(x.error);setData(x);},[entryId]);useEffect(()=>{void load().catch(e=>setMessage(String(e)));},[load]);if(!data.entry)return <p>{message||"Loading…"}</p>;const e=data.entry;
 return <main className="knowledgeEntryView" dir={lang==="ar"?"rtl":"ltr"}><header><Link href="/admin/knowledge">← Knowledge Base</Link><h1>{e.title}</h1><p>{e.summary}</p></header><dl className="knowledgeEntryMeta">{Object.entries({domain:e.domain,kind:e.kind,status:e.status,confidence:e.confidence,freshness:e.freshness,locale:e.locale??"—"}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>{e.content&&<section><h2>Content</h2><p>{e.content}</p></section>}<section><h2>Scope</h2><pre>{JSON.stringify(e.scope,null,2)}</pre></section><section><h2>Sources</h2><ul>{e.sourceRefs.map(source=><li key={`${source.sourceType}:${source.sourceId}`}><strong>{source.sourceType}</strong> · {source.sourceId} · {source.sourceVersion??"current"}</li>)}</ul></section><section><h2>Related entities</h2><ul>{e.relatedEntityRefs.map(ref=><li key={`${ref.entityType}:${ref.entityId}`}>{ref.entityType}: {ref.entityId}</li>)}</ul></section><section><h2>Verification history</h2><ol>{e.reviews.map((review,index)=><li key={`${review.timestamp}:${index}`}>{review.decision} · {review.reviewer} · {new Date(review.timestamp).toLocaleString(lang)}</li>)}</ol></section><section className="knowledgeGraph"><header><h2>Focused Knowledge Graph</h2><button onClick={()=>setExpanded(value=>!value)}>{expanded?"Collapse":"Expand"}</button></header>{expanded&&<div><article><strong>{e.title}</strong><span>{e.domain}</span></article>{data.related?.slice(0,20).map(item=><article key={item.id}><Link href={`/admin/knowledge/${item.id}`}>{item.title}</Link><span>{item.domain}</span></article>)}</div>}</section></main>;
}
