import type { ConversationInputMode, ConversationOutputMode, ResolvedConversationContext, TextOutput } from "./types.ts";
export interface ConversationInputAdapter{readonly mode:ConversationInputMode;available:boolean;normalize(input:unknown):Promise<{text:string;metadata:Record<string,unknown>}>;}
export interface VoiceInputAdapter extends ConversationInputAdapter{readonly mode:"voice";startListening():Promise<void>;stopListening():Promise<{finalTranscript:string}>;cancel():Promise<void>;onPartialTranscript?(listener:(text:string)=>void):()=>void;}
export interface ConversationOutputAdapter<TOutput=unknown>{readonly mode:ConversationOutputMode;available:boolean;deliver(text:string,context:ResolvedConversationContext):Promise<TOutput>;}
export interface SpeechOutputAdapter extends ConversationOutputAdapter{readonly mode:"speech";play():Promise<void>;pause():Promise<void>;stop():Promise<void>;resume():Promise<void>;setPlaybackSpeed(speed:number):Promise<void>;getProgress():Promise<{current:number;duration:number}>;}
export interface AvatarOutputAdapter extends ConversationOutputAdapter{readonly mode:"avatar";connect():Promise<void>;disconnect():Promise<void>;}
export interface HumanCompanionOutputAdapter extends ConversationOutputAdapter{readonly mode:"human";requestHandoff(reason:string):Promise<{requestId:string;status:"pending"}>;}
export const textInputAdapter:ConversationInputAdapter={mode:"text",available:true,async normalize(input){if(typeof input!=="string"||!input.trim())throw new Error("CONVERSATION_TEXT_REQUIRED");return{text:input.trim().slice(0,10000),metadata:{inputMode:"text"}};}};
export const textOutputAdapter:ConversationOutputAdapter<TextOutput>={mode:"text",available:true,async deliver(text,context){const links=[...text.matchAll(/\[([^\]]+)\]\((\/[^)]+)\)/g)].map(match=>({label:match[1],href:match[2]}));return{adapter:"text",format:"markdown",text,direction:context.direction,suggestions:context.language==="ar"?["اشرح هذه الصفحة","اقرأ هذه الصفحة","ساعدني"]:["Explain this page","Read this page","Help me"],links,supports:{markdown:true,links:true,lists:true,codeBlocks:true}};}};
export const unavailableVoiceInputAdapter:VoiceInputAdapter={mode:"voice",available:false,async normalize(){throw new Error("VOICE_INPUT_PROVIDER_UNAVAILABLE");},async startListening(){throw new Error("VOICE_INPUT_PROVIDER_UNAVAILABLE");},async stopListening(){throw new Error("VOICE_INPUT_PROVIDER_UNAVAILABLE");},async cancel(){}};
