import type{CurrentUserSession}from"../auth/sessionTypes.ts";import{knowledgePermissions}from"../knowledge/security.ts";import{isKnownParticipant}from"../participants/registry.ts";import{getPageDesign}from"../page-designs/store.ts";import{resolveNetworkConfiguration}from"../page-designs/networkStore.ts";import{smartServicePermissions}from"../smart-services/security.ts";import{smartServiceRegistry}from"../smart-services/registry.ts";import type{ConversationPageContext,ResolvedConversationContext}from"./types.ts";
export class ContextResolver{
 resolve(actor:CurrentUserSession,page:ConversationPageContext):ResolvedConversationContext{
  const participantId=actor.role==="participant"?actor.participantId:page.participantId;if(actor.role==="participant"&&page.participantId&&page.participantId!==actor.participantId)throw new Error("CONVERSATION_PARTICIPANT_SCOPE_DENIED");if(participantId&&!isKnownParticipant(participantId))throw new Error("CONVERSATION_PARTICIPANT_NOT_FOUND");
  const design=page.designId?getPageDesign(page.designId):undefined;if(actor.role==="participant"&&design?.sourcePage!=="participant")throw new Error("CONVERSATION_DESIGN_SCOPE_DENIED");
  const resolvedConfiguration=resolveNetworkConfiguration({pageType:page.pageType==="admin"?"admin":"participant",participantId,designId:page.designId});const service=page.serviceId?smartServiceRegistry.get(page.serviceId as Parameters<typeof smartServiceRegistry.get>[0]):undefined;const serviceContext={session:actor,participantId,resolvedConfiguration};
  const permissions=[...knowledgePermissions(actor),...smartServicePermissions(actor),...(actor.role==="admin"?["page_designs.view","page_designs.edit","mission_control.view"]:[])];
  return{page:{...page,participantId},currentDesign:design?{id:design.id,name:design.name,status:design.status}:undefined,currentService:service?{id:service.id,status:service.status(serviceContext)}:undefined,currentComponent:page.componentId,participantId,permissions,language:page.locale,direction:page.locale==="ar"?"rtl":"ltr",knowledgeScope:actor.role==="participant"?{visibility:"individual_participant",pageType:"participant",participantId:actor.participantId}:{visibility:"admin_team",pageType:page.pageType==="participant"?"participant":"admin",participantId},actor,availableServices:smartServiceRegistry.list().filter(item=>item.permissions.every(permission=>permissions.includes(permission))).map(item=>item.id)};
 }
}
