import {randomUUID}from"node:crypto";import type{CurrentUserSession}from"../auth/sessionTypes.ts";import type{ConversationMessage,ConversationPageContext,ConversationSession,ConversationTemporaryMemory}from"./types.ts";
const identity=(actor:CurrentUserSession)=>`${actor.role}:${actor.participantId??actor.name??"anonymous"}`;
export class ConversationManager{
 private sessions=new Map<string,ConversationSession>();private owners=new Map<string,string>();
 create(actor:CurrentUserSession,page:ConversationPageContext){if(actor.role==="participant"&&page.participantId&&page.participantId!==actor.participantId)throw new Error("CONVERSATION_PARTICIPANT_SCOPE_DENIED");const timestamp=new Date().toISOString();const session:ConversationSession={sessionId:randomUUID(),participantId:actor.role==="participant"?actor.participantId:page.participantId,pageId:page.pageId,pageType:page.pageType,designId:page.designId,serviceId:page.serviceId,componentId:page.componentId,locale:page.locale,startedAt:timestamp,lastActivity:timestamp,activeInput:"text",activeOutput:"text",state:"active",temporaryMemory:{previousQuestions:[]},messages:[]};this.sessions.set(session.sessionId,session);this.owners.set(session.sessionId,identity(actor));return structuredClone(session);}
 get(sessionId:string,actor:CurrentUserSession){const session=this.sessions.get(sessionId);if(!session)throw new Error("CONVERSATION_SESSION_NOT_FOUND");if(this.owners.get(sessionId)!==identity(actor))throw new Error("CONVERSATION_SESSION_ACCESS_DENIED");return session;}
 addMessage(sessionId:string,actor:CurrentUserSession,input:Omit<ConversationMessage,"id"|"timestamp">){const session=this.get(sessionId,actor);if(session.state==="ended")throw new Error("CONVERSATION_SESSION_ENDED");const message:ConversationMessage={...input,id:randomUUID(),timestamp:new Date().toISOString()};session.messages.push(message);session.messages=session.messages.slice(-200);session.lastActivity=message.timestamp;return structuredClone(message);}
 updateMessage(sessionId:string,actor:CurrentUserSession,messageId:string,input:Partial<Pick<ConversationMessage,"processingState"|"metadata"|"text">>){const session=this.get(sessionId,actor);const message=session.messages.find(item=>item.id===messageId);if(!message)throw new Error("CONVERSATION_MESSAGE_NOT_FOUND");Object.assign(message,input);session.lastActivity=new Date().toISOString();return structuredClone(message);}
 updateMemory(sessionId:string,actor:CurrentUserSession,input:Partial<ConversationTemporaryMemory>){const session=this.get(sessionId,actor);session.temporaryMemory={...session.temporaryMemory,...structuredClone(input),previousQuestions:(input.previousQuestions??session.temporaryMemory.previousQuestions).slice(-20)};session.lastActivity=new Date().toISOString();return structuredClone(session.temporaryMemory);}
 setState(sessionId:string,actor:CurrentUserSession,state:ConversationSession["state"]){const session=this.get(sessionId,actor);session.state=state;session.lastActivity=new Date().toISOString();}
 end(sessionId:string,actor:CurrentUserSession){const session=this.get(sessionId,actor);session.state="ended";session.temporaryMemory={previousQuestions:[]};session.messages=[];session.lastActivity=new Date().toISOString();this.sessions.delete(sessionId);this.owners.delete(sessionId);}
 count(){return this.sessions.size;}
}
export const conversationManager=new ConversationManager();
