import{echoBrainDesignAvailability}from"../page-designs/echobrainStatus.ts";import{getKnowledgeExplanationContext}from"../knowledge/retrieval.ts";import{detectCommand}from"./commandDetector.ts";import{ReadingService}from"./readingService.ts";import type{ConversationSession,ResolvedConversationContext}from"./types.ts";import type{ReasoningOutcome}from"./orchestrator/types.ts";
export type PipelineResult={text:string;messageType:"text"|"command"|"explanation";command:ReturnType<typeof detectCommand>;memory:{currentTopic?:string;lastExplanation?:string;pendingCommand?:ReturnType<typeof detectCommand>};state?:ConversationSession["state"];metadata:Record<string,unknown>};
export class ResponsePipeline{
 private reading=new ReadingService();
 async run(input:{text:string;context:ResolvedConversationContext;session:ConversationSession;reasoning?:ReasoningOutcome}):Promise<PipelineResult>{
  const command=detectCommand(input.text);const ar=input.context.language==="ar";const base={command,metadata:{pageId:input.context.page.pageId,pageType:input.context.page.pageType,designId:input.context.currentDesign?.id,serviceId:input.context.currentService?.id,componentId:input.context.currentComponent,participantId:input.context.participantId,knowledgeScope:input.context.knowledgeScope,echoBrainAvailable:echoBrainDesignAvailability.available}};
  if(command.type==="read_page"){if(!input.context.page.readableContent)return{...base,text:ar?"لا يتوفر محتوى منظم قابل للقراءة لهذه الصفحة.":"No structured readable content is available for this page.",messageType:"explanation",memory:{currentTopic:"page-reading",pendingCommand:command}};const reading=this.reading.read(input.context.page.readableContent,input.context.language);const text=this.reading.toMarkdown(reading);return{...base,text,messageType:"explanation",state:"reading",memory:{currentTopic:"page-reading",lastExplanation:text,pendingCommand:command},metadata:{...base.metadata,reading:{wordCount:reading.wordCount,blockCount:reading.blocks.length}}};}
  if(command.type==="stop_reading")return{...base,text:ar?"تم إيقاف القراءة مؤقتًا.":"Reading paused.",messageType:"command",state:"paused",memory:{pendingCommand:command}};
  if(command.type==="continue_reading")return{...base,text:input.session.temporaryMemory.lastExplanation??(ar?"لا توجد قراءة سابقة للمتابعة.":"There is no previous reading to continue."),messageType:"command",state:"reading",memory:{currentTopic:"page-reading",pendingCommand:command}};
  if(command.type==="open_settings"){const href=input.context.actor.role==="admin"?"/admin/settings":"/participant/settings";return{...base,text:ar?`يمكنك فتح [الإعدادات](${href}).`:`Open [Settings](${href}).`,messageType:"command",memory:{currentTopic:"settings",pendingCommand:command},metadata:{...base.metadata,structuredAction:{type:"navigate",href,requiresUserAction:true}}};}
  if(command.type==="help")return{...base,text:ar?"يمكنني شرح الصفحة، قراءة محتواها المنظم، شرح الإعدادات والتصاميم، أو فتح الإعدادات بأمر منظم.":"I can explain this page, read its structured content, explain settings and designs, or create a structured navigation action for Settings.",messageType:"explanation",memory:{currentTopic:"help",lastExplanation:"capabilities"}};
  if(command.type==="explain_page"){
   const entries=getKnowledgeExplanationContext(input.context.actor,{scope:input.context.knowledgeScope,domains:["platform","design","component","service","participant"],limit:8});const citations=entries.map(entry=>`- ${entry.title}: ${entry.summary} _(source: ${entry.sourceRefs.map(source=>source.sourceId).join(", ")})_`).join("\n");const text=citations?(ar?`## شرح الصفحة\n\n${citations}`:`## Page explanation\n\n${citations}`):(ar?"لا توجد معرفة موثقة ومصرح بها تشرح هذه الصفحة بعد.":"No verified, authorized knowledge explains this page yet.");return{...base,text,messageType:"explanation",memory:{currentTopic:"page-explanation",lastExplanation:text},metadata:{...base.metadata,knowledgeEntryCount:entries.length,verifiedKnowledgeOnly:true}};
  }
  if(input.reasoning)return{...base,text:input.reasoning.response.text,messageType:input.reasoning.response.type==="explanation"?"explanation":"text",memory:{currentTopic:input.text.slice(0,120)},metadata:{...base.metadata,responseSource:input.reasoning.providerAvailable?"echobrain":"safe-unavailable-response",reasoning:{providerId:input.reasoning.providerId,providerAvailable:input.reasoning.providerAvailable,knowledgeAvailable:input.reasoning.knowledgeAvailable,confidence:input.reasoning.response.confidence,missingContext:input.reasoning.response.missingContext,knowledgeSources:input.reasoning.response.knowledgeSources,suggestedFollowUp:input.reasoning.response.suggestedFollowUp,actions:input.reasoning.response.actions}}};
  return{...base,text:echoBrainDesignAvailability.available?(ar?"تم إرسال الطلب إلى EchoBrain.":"The request was routed to EchoBrain."):(ar?"خدمة EchoBrain للمحادثة غير متاحة حاليًا. لم يتم إنشاء إجابة اصطناعية. يمكنك استخدام أوامر الشرح أو قراءة الصفحة المعتمدة على المعرفة الموثقة.":"The EchoBrain conversation backend is currently unavailable. No fabricated AI answer was generated. You can use page explanation or structured reading commands backed by verified knowledge."),messageType:"text",memory:{currentTopic:input.text.slice(0,120)},metadata:{...base.metadata,responseSource:echoBrainDesignAvailability.available?"echobrain":"safe-unavailable-response"}};
 }
}
