"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Bell, Bot, Boxes, LayoutTemplate, PackageSearch } from "lucide-react";
import { useLanguage } from "../../../components/LanguageProvider";
import HomepageSurface from "../../../components/home-v2/HomepageSurface";
import type { InterfaceCategory, PageInterface, SmartServiceContract } from "../../../../lib/smart-services/types";

type ServiceView=Pick<SmartServiceContract,"id"|"name"|"description"|"permissions"|"actions"|"settings">&{status:string;health:{score:number;state:string;checkedAt:string;details:string[]};analytics:Record<string,number>};
type ResponseData={services?:ServiceView[];interfaces?:PageInterface[];aiStatus?:Record<string,unknown>;notifications?:{id:string;type:string;createdAt:string;label:string}[];error?:string;analysis?:Record<string,unknown>};
const categories:InterfaceCategory[]=["current","free","new","recommended","private","purchased","requested"];
const words={ar:{title:"الخدمات الذكية",subtitle:"طبقة إرشادية تقرأ الشبكة ولا تملك حالة الصفحات.",interfaces:"واجهات الصفحة",preview:"معاينة",activate:"طلب التفعيل",request:"طلب واجهة جديدة",product:"نموذج المنتج الذكي",analyze:"تحليل المسودة",companion:"الرفيق الذكي",ask:"اسأل",notifications:"مركز الإشعارات",status:"حالة الذكاء الاصطناعي",offline:"خدمة EchoBrain غير متاحة — لن تُنشأ إجابات وهمية."},en:{title:"Smart Services",subtitle:"An advisory layer that reads the network and never owns page state.",interfaces:"Page Interfaces",preview:"Preview",activate:"Request activation",request:"Request New Interface",product:"Smart Product Form",analyze:"Analyze Draft",companion:"AI Companion",ask:"Ask",notifications:"Notification Center",status:"AI Service Status",offline:"EchoBrain is unavailable — no fabricated responses are generated."}}as const;
export default function SmartServicesDashboard(){
 const{lang}=useLanguage();const t=lang==="ar"?words.ar:words.en;const[data,setData]=useState<ResponseData>({});const[message,setMessage]=useState("");const[draft,setDraft]=useState({title:"",description:"",price:"",images:""});const[analysis,setAnalysis]=useState<Record<string,unknown>>();const[question,setQuestion]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/smart-services",{cache:"no-store"});const x=await r.json()as ResponseData;if(!r.ok)throw new Error(x.error);setData(x);},[]);useEffect(()=>{void load().catch(e=>setMessage(String(e)));},[load]);
 async function post(body:Record<string,unknown>){setMessage("");const r=await fetch("/api/smart-services",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json()as ResponseData;if(!r.ok){setMessage(x.error??"failed");return x;}await load();return x;}
 const ai=useMemo(()=>data.services?.find(service=>service.id==="ai-status"),[data.services]);
 return <main className="smartServicesDashboard" dir={lang==="ar"?"rtl":"ltr"}><header><h1>{t.title}</h1><p>{t.subtitle}</p></header>{message&&<p role="alert" className="pageDesignError">{message}</p>}
 <section><h2><Boxes aria-hidden/>{t.title}</h2><div className="smartServiceGrid">{data.services?.map(service=><HomepageSurface as="article" className="smartServiceCard" key={service.id}><header><h3>{service.name[lang==="ar"?"ar":"en"]}</h3><span data-status={service.status}>{service.status}</span></header><p>{service.description[lang==="ar"?"ar":"en"]}</p><meter min="0" max="100" value={service.health.score}/><small>Health {service.health.score}% · {service.actions.length} actions · auto-publish: disabled</small></HomepageSurface>)}</div></section>
 <section><h2><LayoutTemplate aria-hidden/>{t.interfaces}</h2>{categories.map(category=><div className="interfaceCategory" key={category}><h3>{category.replace("_"," ")}</h3><div>{data.interfaces?.filter(item=>item.category===category).map(item=><article key={item.id}><strong>{item.name}</strong><span>{item.activationStatus}</span><a href={`/admin/page-designs/${item.sourceDesignId}/preview`}>{t.preview}</a><button disabled={item.activationStatus==="pending_approval"} onClick={()=>void post({action:"request_interface_activation",interfaceId:item.id})}>{t.activate}</button></article>)}</div></div>)}<button onClick={()=>void post({action:"request_new_interface"})}>{t.request}</button></section>
 <section><h2><PackageSearch aria-hidden/>{t.product}</h2><div className="smartProductForm"><input placeholder="Title" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/><textarea placeholder="Description" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><input placeholder="Price" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/><input placeholder="Image reference" value={draft.images} onChange={e=>setDraft({...draft,images:e.target.value})}/><button onClick={()=>void post({action:"analyze_product",draft:{...draft,images:draft.images?[draft.images]:[]}}).then(x=>setAnalysis(x.analysis))}>{t.analyze}</button>{analysis&&<pre>{JSON.stringify(analysis,null,2)}</pre>}</div></section>
 <section><h2><Activity aria-hidden/>{t.status}</h2><div className="aiStatusGrid">{Object.entries(data.aiStatus??{}).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value??"—")}</dd></div>)}</div><p>{ai?.status==="offline"&&t.offline}</p></section>
 <section><h2><Bot aria-hidden/>{t.companion}</h2><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder={t.ask}/><button disabled={!question.trim()} onClick={()=>void post({action:"ask_ai",question})}>{t.ask}</button><p>{t.offline}</p></section>
 <section><h2><Bell aria-hidden/>{t.notifications}</h2><ol className="smartNotificationList">{data.notifications?.map(item=><li key={item.id}><strong>{item.label}</strong><span>{item.type} · {new Date(item.createdAt).toLocaleString(lang)}</span></li>)}</ol></section>
 </main>;
}
