"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, BookOpen, GitBranch, HeartPulse, Search } from "lucide-react";
import { useLanguage } from "../../components/LanguageProvider";
import type { KnowledgeDomain, KnowledgeEntry, KnowledgePermission } from "../../../lib/knowledge/types";

type Item=KnowledgeEntry&{freshness:string;sourceCount:number;relationshipCount:number};
type Data={result?:{items:Item[];total:number;page:number;pageSize:number;semanticBackendAvailable:boolean};permissions?:KnowledgePermission[];domains?:KnowledgeDomain[];health?:Record<string,number>;conflicts?:unknown[];error?:string};
const words={ar:{title:"قاعدة المعرفة",overview:"نظرة عامة",search:"بحث",domains:"المجالات",recent:"المعرفة الحديثة",pending:"بانتظار التحقق",conflicts:"التعارضات",deprecated:"المعرفة المهملة",relationships:"العلاقات",sources:"المصادر",health:"صحة المعرفة",backfill:"استيراد السجلات التشغيلية",verify:"تحقق",semantic:"البحث الدلالي غير متاح؛ البحث المنظم والكلمات المفتاحية يعملان."},en:{title:"Knowledge Base",overview:"Overview",search:"Search",domains:"Domains",recent:"Recent Knowledge",pending:"Pending Verification",conflicts:"Conflicts",deprecated:"Deprecated Knowledge",relationships:"Relationships",sources:"Sources",health:"Knowledge Health",backfill:"Ingest Operational Records",verify:"Verify",semantic:"Semantic backend unavailable; structured and keyword search remain active."}}as const;
export default function KnowledgeExplorer(){
 const{lang}=useLanguage();const t=lang==="ar"?words.ar:words.en;const[query,setQuery]=useState("");const[domain,setDomain]=useState("");const[status,setStatus]=useState("");const[page,setPage]=useState(1);const[data,setData]=useState<Data>({});const[health,setHealth]=useState<Record<string,number>>({});const[conflicts,setConflicts]=useState<unknown[]>([]);const[message,setMessage]=useState("");
 const load=useCallback(async()=>{const params=new URLSearchParams({q:query,page:String(page),pageSize:"20"});if(domain)params.set("domain",domain);if(status)params.set("status",status);const r=await fetch(`/api/knowledge?${params}`,{cache:"no-store"});const x=await r.json()as Data;if(!r.ok)throw new Error(x.error);setData(x);},[query,domain,status,page]);
 useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setMessage(String(e))),250);return()=>clearTimeout(timer);},[load]);
 useEffect(()=>{void fetch("/api/knowledge?mode=health").then(r=>r.json()).then((x:Data)=>setHealth(x.health??{}));void fetch("/api/knowledge?mode=conflicts").then(r=>r.json()).then((x:Data)=>setConflicts(x.conflicts??[]));},[]);
 async function post(body:Record<string,unknown>){setMessage("");const r=await fetch("/api/knowledge",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json()as Data;if(!r.ok){setMessage(x.error??"failed");return;}await load();}
 const canVerify=data.permissions?.includes("knowledge.verify");const grouped=useMemo(()=>Object.fromEntries((data.domains??[]).map(item=>[item,data.result?.items.filter(entry=>entry.domain===item).length??0])),[data]);
 return <main className="knowledgeExplorer" dir={lang==="ar"?"rtl":"ltr"}><header><div><h1><BookOpen aria-hidden/>{t.title}</h1><p>{t.semantic}</p></div><button onClick={()=>void post({action:"backfill"})}>{t.backfill}</button></header>{message&&<p className="pageDesignError" role="alert">{message}</p>}
 <nav aria-label="Knowledge sections">{[["overview",t.overview],["search",t.search],["domains",t.domains],["recent",t.recent],["pending",t.pending],["conflicts",t.conflicts],["deprecated",t.deprecated],["relationships",t.relationships],["sources",t.sources],["health",t.health]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
 <section id="overview"><h2>{t.overview}</h2><div className="knowledgeMetrics">{Object.entries(health).map(([key,value])=><article key={key}><dt>{key}</dt><dd>{value}</dd></article>)}</div></section>
 <section id="search"><h2><Search aria-hidden/>{t.search}</h2><div className="knowledgeFilters"><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder={t.search}/><select value={domain} onChange={e=>setDomain(e.target.value)}><option value="">{t.domains}</option>{data.domains?.map(item=><option key={item}>{item}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Status</option><option>draft</option><option>verified</option><option>deprecated</option><option>superseded</option></select></div></section>
 <section id="domains"><h2>{t.domains}</h2><div className="knowledgeDomainGrid">{Object.entries(grouped).map(([name,count])=><article key={name}><strong>{name}</strong><span>{count}</span></article>)}</div></section>
 <section id="recent"><h2>{t.recent}</h2><div className="knowledgeResults">{data.result?.items.map(entry=><article key={entry.id}><header><div><span>{entry.domain} · {entry.kind}</span><h3>{entry.title}</h3></div><span data-freshness={entry.freshness}>{entry.status} · {entry.confidence} · {entry.freshness}</span></header><p>{entry.summary}</p><footer><span>{entry.sourceCount} sources · {entry.relationshipCount} relationships</span><Link href={`/admin/knowledge/${entry.id}`}>Open</Link>{entry.status==="draft"&&canVerify&&<button onClick={()=>void post({action:"verify",id:entry.id,evidence:entry.sourceRefs.map(source=>source.sourceId)})}>{t.verify}</button>}</footer></article>)}</div><div className="knowledgePagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}>‹</button><span>{page} / {Math.max(1,Math.ceil((data.result?.total??0)/20))}</span><button disabled={page*20>=(data.result?.total??0)} onClick={()=>setPage(value=>value+1)}>›</button></div></section>
 <section id="pending"><h2>{t.pending}</h2><p>{data.result?.items.filter(entry=>entry.status==="draft").length??0}</p></section>
 <section id="conflicts"><h2><AlertTriangle aria-hidden/>{t.conflicts}</h2><p>{conflicts.length}</p></section>
 <section id="deprecated"><h2>{t.deprecated}</h2><button onClick={()=>setStatus("deprecated")}>{t.deprecated}</button></section>
 <section id="relationships"><h2><GitBranch aria-hidden/>{t.relationships}</h2><p>{data.result?.items.reduce((sum,item)=>sum+item.relationshipCount,0)??0}</p></section>
 <section id="sources"><h2>{t.sources}</h2><p>{data.result?.items.reduce((sum,item)=>sum+item.sourceCount,0)??0}</p></section>
 <section id="health"><h2><HeartPulse aria-hidden/>{t.health}</h2><div className="knowledgeMetrics">{Object.entries(health).map(([key,value])=><article key={key}><dt>{key}</dt><dd>{value}</dd></article>)}</div></section>
 </main>;
}
