"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useLanguage } from "../../../components/LanguageProvider";
import type { PageDesign, PageDesignPermission } from "../../../../lib/page-designs/types";
import PartialNetworkPanel from "./PartialNetworkPanel";

const labels={ar:{back:"العودة",save:"حفظ المسودة",preview:"معاينة",tests:"تشغيل الاختبارات",request:"طلب الاعتماد",approve:"اعتماد",reject:"رفض",changes:"طلب تعديل",publish:"نشر",rollback:"استرجاع",overview:"ملخص التصميم",ai:"الذكاء الاصطناعي",proposals:"التعديلات المقترحة",previewTab:"المعاينة",results:"نتائج الاختبارات",versions:"سجل الإصدارات",release:"النشر والاسترجاع",enable:"تفعيل الذكاء الاصطناعي",placeholder:"اكتب التعديل المطلوب على هذا التصميم",analyze:"تحليل",apply:"تطبيق على التصميم المعزول",warning:"لن يتم تعديل الإنتاج. المراجعة والتطبيق والاختبارات منفصلة.",unavailable:"خدمة EchoBrain الخلفية غير متاحة حاليًا.",restore:"استعادة إلى مسودة",confirm:"أؤكد النشر إلى الصفحة الحية"},en:{back:"Back",save:"Save Draft",preview:"Preview",tests:"Run Tests",request:"Request Approval",approve:"Approve",reject:"Reject",changes:"Request Changes",publish:"Publish",rollback:"Rollback",overview:"Design Overview",ai:"AI Assistant",proposals:"Proposed Changes",previewTab:"Preview",results:"Test Results",versions:"Version History",release:"Publish and Rollback",enable:"Enable AI",placeholder:"Describe the requested change to this design",analyze:"Analyze",apply:"Apply to isolated design",warning:"Production is not modified. Review, apply, and testing are separate.",unavailable:"EchoBrain design backend is currently unavailable.",restore:"Restore into draft",confirm:"I confirm publishing to the live page"}} as const;
type Result={design?:PageDesign;permissions?:PageDesignPermission[];echoBrainAvailable?:boolean;error?:string};
export default function DesignWorkspace({designId}:{designId:string}){
 const{lang}=useLanguage();const t=lang==="ar"?labels.ar:labels.en;const[design,setDesign]=useState<PageDesign>();const[permissions,setPermissions]=useState<PageDesignPermission[]>([]);const[echo,setEcho]=useState(false);const[prompt,setPrompt]=useState("");const[message,setMessage]=useState("");const[confirmed,setConfirmed]=useState(false);
 const load=useCallback(async()=>{const r=await fetch(`/api/admin/page-designs?id=${encodeURIComponent(designId)}`,{cache:"no-store"});const x=await r.json()as Result;if(!r.ok)throw new Error(x.error);setDesign(x.design);setPermissions(x.permissions??[]);setEcho(Boolean(x.echoBrainAvailable));},[designId]);
 useEffect(()=>{void load().catch(e=>setMessage(String(e)));},[load]);const can=(p:PageDesignPermission)=>permissions.includes(p);
 async function cmd(action:string,extra:Record<string,unknown>={}){setMessage("");const r=await fetch("/api/admin/page-designs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,id:designId,...extra})});const x=await r.json()as Result;if(!r.ok){setMessage(x.error??"failed");return;}setDesign(x.design);}
 const requiredPassed=useMemo(()=>Boolean(design?.tests.every(x=>!x.required||x.state==="passed")),[design]);
 if(!design)return <div className="pageDesignWorkspace">{message||"Loading…"}</div>;
 return <main className="pageDesignWorkspace pageDesignPhase2" dir={lang==="ar"?"rtl":"ltr"}>
  <header className="pageDesignWorkspaceHeader"><div><h1>{design.name}</h1><p>{design.sourcePage} · {design.status} · v{design.versions.at(-1)?.versionNumber} · {new Date(design.updatedAt).toLocaleString(lang)} · AI: {design.aiState}</p></div><div className="pageDesignWorkspaceActions"><Link href="/admin/page-designs">{t.back}</Link><button disabled={!can("page_designs.edit")} onClick={()=>void cmd("save",{layoutNotes:design.settings.layoutNotes,files:design.files})}>{t.save}</button><Link href={`/admin/page-designs/${design.id}/preview`}>{t.preview}</Link><button disabled={!can("page_designs.test")} onClick={()=>void cmd("run_tests")}>{t.tests}</button>{requiredPassed&&design.status!=="approved"&&<button disabled={!can("page_designs.review")} onClick={()=>void cmd("request_approval")}>{t.request}</button>}{design.status==="awaiting_approval"&&<><button disabled={!can("page_designs.approve")} onClick={()=>void cmd("review",{decision:"approved"})}>{t.approve}</button><button disabled={!can("page_designs.approve")} onClick={()=>void cmd("review",{decision:"rejected"})}>{t.reject}</button><button disabled={!can("page_designs.approve")} onClick={()=>void cmd("review",{decision:"changes_requested"})}>{t.changes}</button></>}</div></header>
  {message&&<p className="pageDesignError" role="alert">{message}</p>}
  <nav className="pageDesignTabs" aria-label="Workspace sections">{[["overview",t.overview],["ai",t.ai],["proposals",t.proposals],["preview",t.previewTab],["tests",t.results],["versions",t.versions],["release",t.release]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
  <section id="overview"><h2>{t.overview}</h2><dl className="pageDesignMeta"><div><dt>Source</dt><dd>{design.sourcePage}</dd></div><div><dt>Status</dt><dd>{design.status}</dd></div><div><dt>Version</dt><dd>{design.versions.length}</dd></div><div><dt>Files</dt><dd>{design.files.length}</dd></div></dl><label>Layout notes<textarea value={design.settings.layoutNotes} onChange={e=>setDesign({...design,settings:{...design.settings,layoutNotes:e.target.value}})}/></label></section>
  <PartialNetworkPanel designId={design.id} lang={lang}/>
  <section id="ai"><h2>{t.ai}</h2>{!design.settings.echoBrainSandbox?<button disabled={!can("page_designs.use_ai")} onClick={()=>void cmd("enable_ai")}>{t.enable}</button>:<><p>{t.warning}</p><textarea placeholder={t.placeholder} value={prompt} onChange={e=>setPrompt(e.target.value)}/><button disabled={!echo||!prompt.trim()||!can("page_designs.use_ai")} onClick={()=>void cmd("analyze",{prompt})}>{t.analyze}</button>{!echo&&<p role="status">{t.unavailable}</p>}</>}</section>
  <section id="proposals"><h2>{t.proposals}</h2>{design.proposals.length===0?<p>—</p>:design.proposals.map(p=><article className="pageDesignProposal" key={p.id}><h3>{p.summary}</h3><p>{p.status}</p><strong>Files</strong><ul>{p.filesAffected.map(x=><li key={x}>{x}</li>)}</ul><strong>Components</strong><ul>{p.componentsAffected.map(x=><li key={x}>{x}</li>)}</ul><strong>Risks</strong><ul>{p.risks.map(x=><li key={x}>{x}</li>)}</ul><strong>Tests</strong><ul>{p.requiredTests.map(x=><li key={x}>{x}</li>)}</ul>{p.status==="proposed"&&<button disabled={!can("page_designs.edit")} onClick={()=>void cmd("apply_proposal",{proposalId:p.id})}>{t.apply}</button>}</article>)}</section>
  <section id="preview"><h2>{t.previewTab}</h2><iframe title={t.previewTab} src={`/admin/page-designs/${design.id}/preview?embed=1`} className="pageDesignPreviewFrame"/></section>
  <section id="tests"><h2>{t.results}</h2><div className="pageDesignTestList">{design.tests.map(x=><article key={x.id} data-state={x.state}><strong>{x.name}</strong><span>{x.state}</span><p>{x.summary}</p>{x.error&&<pre>{x.error}</pre>}</article>)}</div></section>
  <section id="versions"><h2>{t.versions}</h2><ol className="pageDesignTimeline">{[...design.versions].reverse().map(v=><li key={v.id}><strong>v{v.versionNumber} · {v.label}</strong><span>{v.createdBy} · {new Date(v.createdAt).toLocaleString(lang)} · {v.trigger}</span><div><Link href={`/admin/page-designs/${design.id}/preview?version=${v.id}`}>{t.preview}</Link><button disabled={!can("page_designs.edit")} onClick={()=>void cmd("restore_version",{versionId:v.id})}>{t.restore}</button></div></li>)}</ol></section>
  <section id="release"><h2>{t.release}</h2><p>Target: /{design.sourcePage} · Required tests: {requiredPassed?"passed":"blocked"} · rollback snapshot: {design.status==="approved"?"created atomically during publish":"pending"}</p>{design.status==="approved"&&<label className="pageDesignConfirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t.confirm}</label>}{design.status==="approved"&&<button disabled={!confirmed||!can("page_designs.publish")} onClick={()=>void cmd("publish",{confirmed:true})}>{t.publish}</button>}{design.status==="published"&&<button disabled={!can("page_designs.rollback")} onClick={()=>confirmed?void cmd("rollback",{confirmed:true}):setMessage(t.confirm)}>{t.rollback}</button>}</section>
 </main>;
}
