"use client";
import { useCallback, useEffect, useState } from "react";
import type {
  DesignNetworkEdge, DesignNetworkNode, DesignScope, PageSectionId,
  ResolvedPageConfiguration, SectionConfiguration,
} from "../../../../lib/page-designs/networkTypes";

const sections:PageSectionId[]=["toolbar","header","announcement","navigation","cards","profile","dialogs","layout","colors","typography"];
const text={ar:{title:"نطاق التصميم",admin:"صفحة المدير كاملة",global:"صفحة المشاركين العامة",group:"مجموعة مشاركين",participant:"مشارك محدد",section:"جزء محدد من الصفحة",search:"البحث بمعرّف المشارك",sandbox:"نسخة خاصة بالمشارك — غير منشورة",save:"حفظ تعديلات النطاق",impact:"تأكيد نطاق التأثير",publish:"نشر التخصيص",previous:"استعادة النسخة السابقة",globalReturn:"العودة إلى التصميم العام",network:"الشبكة الجزئية",inherited:"الإعدادات الموروثة",overrides:"التعديلات الخاصة",expand:"توسيع الفرع",collapse:"طي الفرع"},en:{title:"Design Scope",admin:"Full Admin Page",global:"Global Participant Page",group:"Participant Group",participant:"Individual Participant",section:"Specific Page Section",search:"Search by participant identifier",sandbox:"Participant-Specific Sandbox — Not Published",save:"Save Scope Overrides",impact:"Confirm Impact Scope",publish:"Publish Override",previous:"Restore Previous Version",globalReturn:"Return to Global Design",network:"Partial Network",inherited:"Inherited Settings",overrides:"Overrides",expand:"Expand branch",collapse:"Collapse branch"}}as const;
type Api={participants?:{participantId:string}[];total?:number;groups?:{id:string;name:string;memberCount:number}[];branch?:{nodes:DesignNetworkNode[];edges:DesignNetworkEdge[]};resolved?:ResolvedPageConfiguration;impact?:{count:number;scope:DesignScope}|null;workspace?:{scope:DesignScope;sections:Partial<SectionConfiguration>};error?:string};
export default function PartialNetworkPanel({designId,lang}:{designId:string;lang:string}){
 const t=lang==="ar"?text.ar:text.en;const[scope,setScope]=useState<DesignScope>({type:"participant_global",sectionIds:["layout"],impactConfirmed:false});const[participantId,setParticipantId]=useState("");const[search,setSearch]=useState("");const[page,setPage]=useState(1);const[participants,setParticipants]=useState<{participantId:string}[]>([]);const[total,setTotal]=useState(0);const[selected,setSelected]=useState<PageSectionId[]>(["layout"]);const[settings,setSettings]=useState("{}");const[data,setData]=useState<Api>();const[expanded,setExpanded]=useState(false);const[message,setMessage]=useState("");
 const load=useCallback(async()=>{const params=new URLSearchParams({designId,pageType:scope.type==="admin_page"?"admin":"participant"});if(participantId)params.set("participantId",participantId);const r=await fetch(`/api/admin/page-designs/network?${params}`,{cache:"no-store"});const x=await r.json()as Api;if(r.ok)setData(x);},[designId,participantId,scope.type]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{const timer=setTimeout(()=>{const params=new URLSearchParams({mode:"participants",search,page:String(page),pageSize:"10"});void fetch(`/api/admin/page-designs/network?${params}`).then(r=>r.json()).then((x:Api)=>{setParticipants(x.participants??[]);setTotal(x.total??0);});},250);return()=>clearTimeout(timer);},[search,page]);
 async function post(action:string,extra:Record<string,unknown>={}){setMessage("");const r=await fetch("/api/admin/page-designs/network",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,designId,...extra})});const x=await r.json()as Api;if(!r.ok){setMessage(x.error??"failed");return;}await load();}
 function effectiveScope():DesignScope{return{...scope,participantId:scope.type==="participant"?participantId:undefined,sectionIds:selected,impactConfirmed:false};}
 async function save(){let parsed:Record<string,unknown>;try{parsed=JSON.parse(settings)as Record<string,unknown>;}catch{setMessage("INVALID_SECTION_SETTINGS");return;}const next=effectiveScope();await post("set_scope",{scope:next});const overrides=Object.fromEntries(selected.map(id=>[id,{enabled:true,settings:parsed,componentVersionId:`${id}-shared`}]))as Partial<SectionConfiguration>;await post("save_sections",{sections:overrides});}
 const impact=data?.impact;return <section id="partial-network" className="partialNetworkPanel"><h2>{t.title}</h2><div className="partialScopeGrid"><label>{t.title}<select value={scope.type} onChange={e=>setScope({...scope,type:e.target.value as DesignScope["type"]})}><option value="admin_page">{t.admin}</option><option value="participant_global">{t.global}</option><option value="participant_group">{t.group}</option><option value="participant">{t.participant}</option><option value="section">{t.section}</option></select></label>{scope.type==="participant"&&<div><label>{t.search}<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><select aria-label={t.participant} value={participantId} onChange={e=>setParticipantId(e.target.value)}><option value="">—</option>{participants.map(item=><option key={item.participantId}>{item.participantId}</option>)}</select><div className="partialPagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>‹</button><span>{page} / {Math.max(1,Math.ceil(total/10))}</span><button disabled={page*10>=total} onClick={()=>setPage(p=>p+1)}>›</button></div></div>}</div>
 {scope.type==="participant_group"&&<label>{t.group}<select value={scope.groupId??""} onChange={e=>setScope({...scope,groupId:e.target.value})}><option value="">—</option>{data?.groups?.map(group=><option key={group.id} value={group.id}>{group.name} ({group.memberCount})</option>)}</select></label>}
 {scope.type==="participant"&&participantId&&<p className="participantSandboxBadge">{t.sandbox}: <bdi>{participantId}</bdi></p>}
 <fieldset><legend>Sections</legend>{sections.map(id=><label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={e=>setSelected(current=>e.target.checked?[...current,id]:current.filter(x=>x!==id))}/>{id}</label>)}</fieldset><label>{t.overrides}<textarea dir="ltr" value={settings} onChange={e=>setSettings(e.target.value)}/></label><button disabled={!selected.length||(scope.type==="participant"&&!participantId)} onClick={()=>void save()}>{t.save}</button>
 {message&&<p role="alert" className="pageDesignError">{message}</p>}{impact&&<div className="partialImpact"><strong>{impact.count===1?(lang==="ar"?"هذا التغيير يؤثر على مشارك واحد فقط":"This change affects one participant only"):impact.count<0?(lang==="ar"?"هذا التغيير يؤثر على جميع المشاركين":"This change affects all participants"):`Impact: ${impact.count}`}</strong><button onClick={()=>void post("confirm_impact")}>{t.impact}</button>{impact.scope.type==="participant"&&<><button onClick={()=>void post("publish_participant")}>{t.publish}</button><button onClick={()=>void post("rollback_participant",{participantId,mode:"previous"})}>{t.previous}</button><button onClick={()=>void post("rollback_participant",{participantId,mode:"global"})}>{t.globalReturn}</button></>}</div>}
 <div className="partialNetworkTree"><header><h3>{t.network}</h3><button onClick={()=>setExpanded(x=>!x)}>{expanded?t.collapse:t.expand}</button></header>{expanded&&<><ol>{data?.branch?.nodes.map(node=><li key={node.id}><span>{node.type}</span><strong>{node.name}</strong></li>)}</ol><details><summary>{t.inherited}</summary><pre>{JSON.stringify(data?.resolved?.inheritance??[],null,2)}</pre></details><details><summary>{t.overrides}</summary><pre>{JSON.stringify(data?.resolved?.sections??{},null,2)}</pre></details></>}</div></section>;
}
