import{randomUUID}from"node:crypto";import{SpeechComposer}from"./composer.ts";import type{SpeechDocument,SpeechLanguage,SpeechSession}from"./types.ts";import type{SpeechQueue}from"./queue.ts";
export class SpeechSessionManager{
 private sessions=new Map<string,SpeechSession>();private introductionDocuments=new Map<string,SpeechDocument>();private queue:SpeechQueue;private composer:SpeechComposer;
 constructor(queue:SpeechQueue,composer=new SpeechComposer()){this.queue=queue;this.composer=composer;}
 create(conversationSessionId:string,language:SpeechLanguage){const timestamp=new Date().toISOString();const session:SpeechSession={id:randomUUID(),conversationSessionId,mode:"introduction",language,createdAt:timestamp,updatedAt:timestamp,state:"idle"};this.sessions.set(session.id,session);return structuredClone(session);}
 prepareIntroduction(sessionId:string,input:{greeting:string;introduction:string;invitation:string}){const session=this.get(sessionId);const text=[input.greeting,input.introduction,input.invitation].filter(Boolean).join("\n\n");const document=this.composer.compose({text,language:session.language,source:{type:"help",sourceId:`introduction:${session.conversationSessionId}`},style:"professional-friendly-calm-natural"});if(document.estimatedDuration>45)throw new Error("SPEECH_INTRODUCTION_TOO_LONG");this.introductionDocuments.set(sessionId,document);session.currentDocumentId=document.id;session.updatedAt=new Date().toISOString();return document;}
 async playIntroduction(sessionId:string){const session=this.get(sessionId);const document=this.introductionDocuments.get(sessionId);if(!document)throw new Error("SPEECH_INTRODUCTION_NOT_PREPARED");await this.queue.enqueue(document);session.state="queued";session.updatedAt=new Date().toISOString();await this.queue.play();session.state="speaking";return structuredClone(session);}
 enableFollowMode(sessionId:string){const session=this.get(sessionId);session.mode="follow";session.introductionAccepted=true;session.updatedAt=new Date().toISOString();return structuredClone(session);}
 async decline(sessionId:string){const session=this.get(sessionId);await this.queue.interrupt("user_stop");session.mode="stopped";session.state="stopped";session.introductionAccepted=false;session.updatedAt=new Date().toISOString();return structuredClone(session);}
 async enqueueContextual(sessionId:string,document:SpeechDocument){const session=this.get(sessionId);if(session.mode!=="follow")throw new Error("SPEECH_FOLLOW_MODE_DISABLED");await this.queue.enqueue(document);session.currentDocumentId=document.id;session.state="queued";session.updatedAt=new Date().toISOString();return structuredClone(session);}
 get(id:string){const session=this.sessions.get(id);if(!session)throw new Error("SPEECH_SESSION_NOT_FOUND");return session;}
}
