"use client";
import{useCallback,useEffect,useState}from"react";
import type{ReactNode}from"react";
import{Activity,AlertTriangle,BookOpen,BrainCircuit,CheckSquare,ClipboardCheck,CloudUpload,Command,Lightbulb,Network,ServerCog,ShieldCheck,Users,Workflow}from"lucide-react";
import{useLanguage}from"../../components/LanguageProvider";
type Dashboard=Record<string,unknown>&{generatedAt:string;platformHealth:Record<string,unknown>;networkHealth:Record<string,unknown>;designOperations:Record<string,unknown>;smartServices:Array<{id:string;name:{ar:string;en:string};status:string;health:{score:number};failures:number}>;knowledgeCenter:Record<string,unknown>;aiOperations:Record<string,unknown>;publishingCenter:Record<string,unknown>&{publishHistory:Array<{id:string;label:string;createdAt:string}>};participantOperations:Record<string,unknown>;alerts:Array<{id:string;severity:string;message:string}>;tasks:Array<{id:string;title:string;priority:string;owner:string;status:string;dueDate?:string}>;approvals:{designs:Array<{id:string;label:string}>;interfaces:number;knowledge:number;commands:unknown[]};timeline:Array<{id:string;type:string;label:string;createdAt:string}>;recommendations:{knowledge:Array<{id:string;title:string;summary:string}>;advisoryOnly:true}};
const labels={ar:{title:"مركز القيادة",platform:"صحة المنصة",network:"صحة الشبكة",designs:"عمليات التصميم",services:"الخدمات الذكية",knowledge:"مركز المعرفة",ai:"عمليات الذكاء الاصطناعي",publishing:"مركز النشر",participants:"عمليات المشاركين",alerts:"التنبيهات",tasks:"المهام",approvals:"الموافقات",timeline:"الخط الزمني",recommendations:"التوصيات",command:"مركز الأوامر",create:"إنشاء مهمة",request:"إرسال طلب الأمر",advisory:"جميع التوصيات استشارية ولا تُنشر تلقائيًا."},en:{title:"Mission Control",platform:"Platform Health",network:"Network Health",designs:"Design Operations",services:"Smart Services",knowledge:"Knowledge Center",ai:"AI Operations",publishing:"Publishing Center",participants:"Participant Operations",alerts:"Alerts",tasks:"Tasks",approvals:"Approvals",timeline:"Activity Timeline",recommendations:"Recommendations",command:"Command Center",create:"Create Task",request:"Submit Command Request",advisory:"All recommendations are advisory and never auto-publish."}}as const;
const icons={platform:ServerCog,network:Network,designs:Workflow,services:ServerCog,knowledge:BookOpen,ai:BrainCircuit,publishing:CloudUpload,participants:Users,alerts:AlertTriangle,tasks:CheckSquare,approvals:ClipboardCheck,timeline:Activity,recommendations:Lightbulb,command:Command};
type SectionId=keyof typeof icons;
function Metrics({data}:{data:Record<string,unknown>}){return <div className="missionMetrics">{Object.entries(data).filter(([,value])=>!Array.isArray(value)&&typeof value!=="object").map(([key,value])=><article key={key}><dt>{key}</dt><dd>{String(value??"—")}</dd></article>)}</div>}
function Section({id,label,children}:{id:SectionId;label:string;children:ReactNode}){const Icon=icons[id];return <section id={id}><h2><Icon aria-hidden/>{label}</h2>{children}</section>}
export default function MissionControlDashboard(){const{lang}=useLanguage();const t=lang==="ar"?labels.ar:labels.en;const[data,setData]=useState<Dashboard>();const[message,setMessage]=useState("");const[task,setTask]=useState({title:"",owner:"",priority:"medium",dueDate:""});const[command,setCommand]=useState({commandType:"",scope:"",impact:"",snapshotId:"",approvalId:"",confirmed:false});
 const load=useCallback(async()=>{const r=await fetch("/api/admin/mission-control",{cache:"no-store"});const x=await r.json()as{dashboard?:Dashboard;error?:string};if(!r.ok)throw new Error(x.error);setData(x.dashboard);},[]);useEffect(()=>{void load().catch(e=>setMessage(String(e)));},[load]);
 async function post(body:Record<string,unknown>){setMessage("");const r=await fetch("/api/admin/mission-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json()as{error?:string};if(!r.ok){setMessage(x.error??"failed");return;}await load();}
 if(!data)return <p>{message||"Loading…"}</p>;
 return <main className="missionControl" dir={lang==="ar"?"rtl":"ltr"}><header><div><h1><ShieldCheck aria-hidden/>{t.title}</h1><p>{new Date(data.generatedAt).toLocaleString(lang)}</p></div><span data-status={String(data.platformHealth.status)}>{String(data.platformHealth.status)}</span></header>{message&&<p role="alert" className="pageDesignError">{message}</p>}
 <nav>{(Object.keys(icons)as Array<keyof typeof icons>).map(id=><a key={id} href={`#${id}`}>{t[id]}</a>)}</nav>
 <Section id="platform" label={t.platform}><Metrics data={data.platformHealth}/></Section><Section id="network" label={t.network}><Metrics data={data.networkHealth}/></Section><Section id="designs" label={t.designs}><Metrics data={data.designOperations}/></Section>
 <Section id="services" label={t.services}><div className="missionCardGrid">{data.smartServices.map(service=><article key={service.id}><strong>{service.name[lang==="ar"?"ar":"en"]}</strong><span>{service.status}</span><meter min="0" max="100" value={service.health.score}/><small>{service.failures} failures</small></article>)}</div></Section>
 <Section id="knowledge" label={t.knowledge}><Metrics data={data.knowledgeCenter}/></Section><Section id="ai" label={t.ai}><Metrics data={data.aiOperations}/></Section><Section id="publishing" label={t.publishing}><Metrics data={data.publishingCenter}/><ol>{data.publishingCenter.publishHistory.map(item=><li key={item.id}>{item.label} · {new Date(item.createdAt).toLocaleString(lang)}</li>)}</ol></Section><Section id="participants" label={t.participants}><Metrics data={data.participantOperations}/></Section>
 <Section id="alerts" label={t.alerts}><div className="missionAlertList">{data.alerts.map(alert=><article key={alert.id} data-severity={alert.severity}><strong>{alert.severity}</strong><span>{alert.message}</span></article>)}</div></Section>
 <Section id="tasks" label={t.tasks}><form onSubmit={e=>{e.preventDefault();void post({action:"create_task",...task});}} className="missionForm"><input required placeholder="Task" value={task.title} onChange={e=>setTask({...task,title:e.target.value})}/><input required placeholder="Owner" value={task.owner} onChange={e=>setTask({...task,owner:e.target.value})}/><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>critical</option></select><input type="date" value={task.dueDate} onChange={e=>setTask({...task,dueDate:e.target.value})}/><button>{t.create}</button></form><div className="missionTaskList">{data.tasks.map(item=><article key={item.id}><strong>{item.title}</strong><span>{item.priority} · {item.owner} · {item.status}</span><button onClick={()=>void post({action:"update_task",id:item.id,status:"completed"})}>Complete</button></article>)}</div></Section>
 <Section id="approvals" label={t.approvals}><div className="missionMetrics"><article><dt>Designs</dt><dd>{data.approvals.designs.length}</dd></article><article><dt>Interfaces</dt><dd>{data.approvals.interfaces}</dd></article><article><dt>Knowledge</dt><dd>{data.approvals.knowledge}</dd></article><article><dt>Commands</dt><dd>{data.approvals.commands.length}</dd></article></div></Section>
 <Section id="timeline" label={t.timeline}><ol className="missionTimeline">{data.timeline.map(item=><li key={`${item.type}:${item.id}`}><strong>{item.label}</strong><span>{item.type} · {new Date(item.createdAt).toLocaleString(lang)}</span></li>)}</ol></Section>
 <Section id="recommendations" label={t.recommendations}><p>{t.advisory}</p><div className="missionCardGrid">{data.recommendations.knowledge.map(item=><article key={item.id}><strong>{item.title}</strong><p>{item.summary}</p></article>)}</div></Section>
 <Section id="command" label={t.command}><form onSubmit={e=>{e.preventDefault();void post({action:"request_command",...command});}} className="missionForm missionCommandForm"><input required placeholder="Command type" value={command.commandType} onChange={e=>setCommand({...command,commandType:e.target.value})}/><input required placeholder="Scope" value={command.scope} onChange={e=>setCommand({...command,scope:e.target.value})}/><input required placeholder="Impact" value={command.impact} onChange={e=>setCommand({...command,impact:e.target.value})}/><input required placeholder="Snapshot ID" value={command.snapshotId} onChange={e=>setCommand({...command,snapshotId:e.target.value})}/><input required placeholder="Approval ID" value={command.approvalId} onChange={e=>setCommand({...command,approvalId:e.target.value})}/><label><input type="checkbox" checked={command.confirmed} onChange={e=>setCommand({...command,confirmed:e.target.checked})}/>Explicit confirmation</label><button disabled={!command.confirmed}>{t.request}</button></form><p>No command executes directly. Requests remain awaiting approval.</p></Section>
 </main>}
